### ISSUE TITLE
Is it better to throw warning instead of FileNotFoundError

### ISSUE THREAD

**Issue by Podidiving** [catalyst-team/catalyst#1009]
## 🚀 Feature Request
when starting training with `autoresume` key 
https://github.com/catalyst-team/catalyst/blob/3126390f9f679ebcfedbe01707b416678a2732ac/catalyst/callbacks/checkpoint.py#L589
here 
https://github.com/catalyst-team/catalyst/blob/3126390f9f679ebcfedbe01707b416678a2732ac/catalyst/callbacks/checkpoint.py#L41t
is called
Maybe, It's better to throw warning instead of FileNotFoundError?

### Motivation
Imagine you have a complex shell script with `catalyst-dl run` with `autoresume` key in the end. You need `autoresume` in case your training is failed and you can resume it. But if you run script for the first time, obviously, you don't have any checkpoints yet. So, you must delete this flag manually. It's kind of inconvenient

**Comment by Scitator** [comment]
There is only one correct way to handle file-not-found during `load_checkpoint` - throw an error :)
For autoresume feature, we could speak about another handling, but I don't know it for now (so, I am open to your proposals :) ). As "some-kind-of-a-solution", you could check your folders during bash script and turn on/off `--autoresume`, I think.
