### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by zkid18** [catalyst-team/catalyst#1011]
## 🐛 Bug Report

While running `pip install -r requirements/requirements.txt -r requirements/requirements-dev.txt` 
`pip` raised the following error. 
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

aws-shell 0.2.2 requires prompt-toolkit<1.1.0,>=1.0.0, but you'll have prompt-toolkit 3.0.8 which is incompatible.
```

I guess we need to check the requirements. 

### How To Reproduce
1. Go to `catalyst`
1. Run `pip install -r requirements/requirements.txt -r requirements/requirements-dev.txt` 

 

### Environment

```bash
Catalyst version: 20.07
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: None
TensorFlow version: N/A
TensorBoard version: 2.2.2

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```

### Additional context

PS
- [x] I know, that I could [join Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion.

**Comment by Scitator** [comment]
Should be fixed here https://github.com/catalyst-team/catalyst/pull/1002

**Comment by Scitator** [comment]
Merged 🎉
