### ISSUE TITLE
ClasswiseIouCallback bug

### ISSUE THREAD

**Issue by sleep3r** [catalyst-team/catalyst#1016]
## 🐛 Bug Report
ClasswiseIouCallback doesn't work, raising **TypeError: iou() got an unexpected keyword argument 'list_args'**

### How To Reproduce
1. Try to use it

#### Code sample
```
    callback: ClasswiseIouCallback
    input_key: mask
    classes: ['one', 'two']
    threshold: 0.5
```

### Environment
Catalyst version: 20.09
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2
TensorFlow version: N/A
TensorBoard version: 2.4.0

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce RTX 2080 Ti

Nvidia driver version: 450.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] catalyst==20.9
[pip3] numpy==1.19.1
[pip3] tensorboard==2.4.0
[pip3] tensorboard-plugin-wit==1.7.0
[pip3] tensorboardX==2.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] catalyst                  20.9                     pypi_0    pypi
[conda] numpy                     1.19.1                   pypi_0    pypi
[conda] tensorboard               2.4.0                    pypi_0    pypi
[conda] tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
[conda] tensorboardx              2.1                      pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

### Additional context
    Actually, BatchMetricCallback tries to call iou() metric fn with list_args argument, as the traceback says.

PS
- [x] I know, that I could [join Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion.

**Comment by Podidiving** [comment]
seems like `list_args` argument is just redundant

**Comment by Scitator** [comment]
🤔  sounds legit,
@sleep3r could you please contribute a minimal example for ClasswiseIouCallback test case, so we could decide the next steps on "how to fix it"?
