### ISSUE TITLE
Typo in activations

### ISSUE THREAD

**Issue by Podidiving** [catalyst-team/catalyst#1020]
## 🐛 Bug Report
https://github.com/catalyst-team/catalyst/blob/ab07c436cf730fb41d75cf6eee250d977379f2a0/catalyst/utils/torch.py#L24
I believe, it should be `nn.ELU: "elu"`

PS
- [x] I know, that I could [join Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion.

**Comment by Scitator** [comment]
this is a trick to resolve this warning:
https://github.com/catalyst-team/catalyst/blob/ab07c436cf730fb41d75cf6eee250d977379f2a0/catalyst/utils/torch.py#L51L52 :)

Nevertheless, yup, it could be done better with more activation functions support
