### ISSUE TITLE
Can't use multiple workers for DataLoader

### ISSUE THREAD

**Issue by alxmamaev** [catalyst-team/catalyst#1024]
## 🐛 Bug Report
I think, that I found a bug
When i try to setup num workers for dataloader> 0 inside ConfigAPi, im getting Can't pickle local object 'get_loaders_from_params. <locals>. <lambda>.

I found the reason for this behavior (link) because we try to put inside a lambda, and lambda is not pickle’iseble object

https://github.com/catalyst-team/catalyst/blob/0a2afda0e90425c206f3ece3a28e347cb58278d3/catalyst/utils/loaders.py#L318-L321

**Comment by Scitator** [comment]
do you have a minimal example to reproduce?
or could you please check https://github.com/catalyst-team/catalyst/blob/master/bin/tests/check_dl_core_callbacks.sh then?
