### ISSUE TITLE
F1 score metric does not work

### ISSUE THREAD

**Issue by alxmamaev** [catalyst-team/catalyst#1026]
When I trying to use F1ScoreCallback, Im getting this error `f1_score() got an unexpected keyword argument 'beta'`

This is happening, because we trying to pass `beta` parameter inside the callback
https://github.com/catalyst-team/catalyst/blob/ccef2c7de7ff3869523a86f291b6a2390308bad5/catalyst/callbacks/metrics/f1_score.py#L31-L40

But the f1_score function doesn't get this param

https://github.com/catalyst-team/catalyst/blob/ccef2c7de7ff3869523a86f291b6a2390308bad5/catalyst/metrics/f1_score.py#L51-L57

**Comment by Scitator** [comment]
duplicate issue :)
