### ISSUE TITLE
WandbLogger image logging and issue fix

### ISSUE THREAD

**Issue by smivv** [catalyst-team/catalyst#1033]
## 🚀 Feature Request

Hello,

First of all I'd like to add possibility to send images, segmentation masks to Wandb.
Also I want to fix small issue: WandbLogger has no possibility to pass `name` through Config API, it crushes.
Description of that bug at the bottom: https://github.com/catalyst-team/catalyst/pull/720

**Comment by Scitator** [comment]
Could you please use our full proposal template? Thanks in advance!
