### ISSUE TITLE
KeyError: 'loss'

### ISSUE THREAD

**Issue by lebionick** [catalyst-team/catalyst#108]
Raises this exception after first epoch. 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-31-eecc50de0067> in <module>
      3     callbacks=callbacks,
      4     logdir=logdir,
----> 5     epochs=n_epochs, verbose=True)

~/miniconda3/lib/python3.6/site-packages/catalyst/dl/runner.py in train(self, loaders, callbacks, state_params, epochs, start_epoch, verbose, logdir)
    214             mode="train",
    215             verbose=verbose,
--> 216             logdir=logdir,
    217         )
    218 

~/miniconda3/lib/python3.6/site-packages/catalyst/dl/runner.py in run(self, loaders, callbacks, state_params, epochs, start_epoch, mode, verbose, logdir)
    180                 self.run_event(callbacks=callbacks, event="on_loader_end")
    181 
--> 182             self.run_event(callbacks=callbacks, event="on_epoch_end")
    183 
    184         self.run_event(callbacks=callbacks, event=f"on_{mode}_end")

~/miniconda3/lib/python3.6/site-packages/catalyst/dl/runner.py in run_event(self, callbacks, event)
     93         :param event:
     94         """
---> 95         getattr(self.state, f"{event}_pre")(state=self.state)
     96         for callback in callbacks.values():
     97             getattr(callback, event)(state=self.state)

~/miniconda3/lib/python3.6/site-packages/catalyst/dl/state.py in on_epoch_end_pre(state)
    146                 valid_loader=state.valid_loader,
    147                 main_metric=state.main_metric,
--> 148                 minimize=state.minimize_metric)
    149         valid_metrics = {
    150             key: value

~/miniconda3/lib/python3.6/site-packages/catalyst/dl/callbacks/utils.py in process_epoch_metrics(epoch_metrics, best_metrics, valid_loader, main_metric, minimize)
     27         if best_metrics is None \
     28         else (minimize != (
---> 29             valid_metrics[main_metric] > best_metrics[main_metric]))
     30     best_metrics = valid_metrics if is_best else best_metrics
     31     return best_metrics, valid_metrics, is_best

KeyError: 'loss'
```
  
I'm using these callbacks:
``` python
callbacks["loss"] = LossCallback()
callbacks["optimizer"] = OptimizerCallback()
callbacks["precision"] = PrecisionCallback(
    precision_args=[1])

callbacks["scheduler"] = SchedulerCallback(
    reduce_metric="precision01")

callbacks["saver"] = CheckpointCallback()
callbacks["logger"] = Logger()
callbacks["tflogger"] = TensorboardLogger()
```
  
Data and processing are taken from here:: https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by TezRomacH** [comment]
Did you define your `main_metric`?
Like here https://github.com/catalyst-team/catalyst/blob/master/examples/finetune/train.yml#L26

**Comment by lebionick** [comment]
@TezRomacH 
Nope. How to do this without .yml, just in python code?

**Comment by Scitator** [comment]
@lebionick Hi, could you please check catalyst version?

**Comment by lebionick** [comment]
@Scitator '19.02-rc0'

**Comment by Scitator** [comment]
Interesting, can you run [notebook example](https://github.com/catalyst-team/catalyst/blob/master/examples/notebook-example.ipynb)?

**Comment by lebionick** [comment]
Tomorrow:)

**Comment by lebionick** [comment]
@Scitator I've run this example and it works just fine.
Meanwhile the same setup of callbacks crashes in pytorch example. However, I spotted interesting inconsistency: in the first run I get 
```
AttributeError: Can't pickle local object 'RunnerState.__init__.<locals>.<lambda>.<locals>.<lambda>'
```
And then it disappears, giving KeyError 'loss'. I thought I's because of "saver" callback, and commented him out.
Without "saver" it crashes after the second epoch(!)
I'll put the code below...

**Comment by lebionick** [comment]
https://yadi.sk/d/12gImIlUex73ZQ

**Comment by Scitator** [comment]
So, as error said you are trying to save something lambda-like -> check model/criterion/etc for that and remove that for code correctness - python still cannot save different users lambdas. You can find the same ants&bees examples catalyst-friendly [here](https://github.com/catalyst-team/catalyst/tree/master/examples/finetune). Btw, advanced one.

For the second one, I have noticed, that you use `val`(instead of `valid`, which is by default in catalyst) for validation loader, so just rename it for simplicity. Looks like we should add asserts for callbacks in 19.02.

**Comment by lebionick** [comment]
@Scitator 
so problem was in 'valid'... saving also works fine
🙈
