### ISSUE TITLE
[solved] How to train with KFold

### ISSUE THREAD

**Issue by ngxbac** [catalyst-team/catalyst#11]
Thank for your awesome library. 
I am wondering if this library supports training with KFold Cross-validation?

**Comment by Scitator** [comment]
Hi,

Long story short, it is available, but not fully automated. 
For now, you can make it by:
1. prepare KFold split in your `DataSource` ([config example](https://github.com/Scitator/catalyst-examples/blob/master/finetune/train.yml#L33), [DataSource example](github.com/Scitator/catalyst-examples/blob/master/finetune/data.py#L96)).
2. add `prepare_logdir` for your `model.py` ([example](https://github.com/Scitator/catalyst-examples/blob/master/finetune/model.py#L57))
3. run some kind of grid search with different `train_folds` ([example](https://github.com/Scitator/catalyst-examples/blob/master/finetune/run_grid.sh))

I think, you can start from this [example](https://github.com/Scitator/catalyst-examples/tree/master/finetune) to figure out how it is all working. Or, simply tune its `prepare_logdir` and `run_grid.sh` for additional `run_kfold.sh` (PR are always welcome 😄 ).

PS. for different `train_folds`  just pass something like `--stages/data_params/train_folds=[1, 2, 3, 4]:list` for `train.py` script. ([example](https://github.com/Scitator/catalyst-examples/blob/master/finetune/run_grid.sh))

**Comment by ngxbac** [comment]
Thank you.  
I got your ideas. It makes sense for me.

**Comment by Scitator** [comment]
examples update:
https://github.com/Scitator/catalyst-examples/tree/master/finetune#kfold-training-metrics-visualization
