### ISSUE TITLE
Model and loader on different devices

### ISSUE THREAD

**Issue by JosianeUwineza** [catalyst-team/catalyst#1132]
## Fixing Request
I would like to ask if it is possible that the loader and model can have the same device so that the prediction stage can work properly in catalyst==21.0

#### Screenshots
![Screenshot from 2021-03-23 12-25-00](https://user-images.githubusercontent.com/75666755/112145889-97781b00-8be3-11eb-9fb3-00f9e526360b.png)
ble, add screenshots to help explain your problem.  -->

### Expected behavior
runner.presict_loader works properly.

**Comment by Scitator** [comment]
Nice catch! Should fix in the upcoming release this month.

**Comment by Scitator** [comment]
should be fixed in master branch in a few hours 🚀 
https://colab.research.google.com/drive/1aTqevoFY8cHRTWctqn_Y4IP6F59DhFWe?usp=sharing

**Comment by JosianeUwineza** [comment]
Great, If it will be fixed soon.

**Comment by Scitator** [comment]
Should be fixed now :)
