### ISSUE TITLE
Add Classifier-Balancing to catalyst.data API

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#1161]
## 🚀 Feature Request

Let's add samplers from [`facebookresearch/classifier-balancing`](https://github.com/facebookresearch/classifier-balancing) to [catalyst.data.sampler](https://github.com/catalyst-team/catalyst/blob/master/catalyst/data/sampler.py).

### Motivation

Catalyst already has a large variety of data samplers – let's compare them with the FB Research one and add them to our Data API.

### Proposal

- review the FB repo
- make a refactoring - make the code cleaner for the implementations
- make a PR for catalyst.data.sampler
- add tests and docs for the community users

### Additional context

This is a great feature request for newcomers – only PyTorch knowledge required :)

### Checklist
- [x] feature proposal description.
- [x] motivation.
- [x] extra proposal context / proposal alternatives review.
- [x] I know, that I could [join Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion.

**Comment by ghost** [comment]
I think, I can handle it

**Comment by Scitator** [comment]
Thank you very much!
Feel free to ask any questions 🚀
