### ISSUE TITLE
SWA can broke because torch.div may be deprecated 

### ISSUE THREAD

**Issue by AlekseySh** [catalyst-team/catalyst#1166]
`torch.div` function is using for swa:
https://github.com/catalyst-team/catalyst/blob/e43c62e9cafdd703d5d35779c7aa90e2be761a34/catalyst/utils/swa.py#L53
(function `average_weights`).

But this function may not work with torch 1.6: [link](https://pytorch.org/docs/1.6.0/generated/torch.div.html?highlight=div)
```
Integer division using div is no longer supported, and in a future release div will perform true division as in Python 3. Use torch.true_divide() or torch.floor_divide() (// in Python), instead.
```
I have checked, that it works with CPU build, but does not work with GPU one (at least in my case).

So, probably, it should be replaced with `true_divide`

**Comment by Scitator** [comment]
could you please provide a minimal example? maybe on google colab?
