### ISSUE TITLE
Resume via CheckpointCallback does not work

### ISSUE THREAD

**Issue by AlekseySh** [catalyst-team/catalyst#1168]
`CheckpointCallback` does not work for resuming train. It does nothing: it does not change the numbers of epochs, batches, etc. (It starts from scratch). It does not load model and optimizer states.

I show the problem to @Ditwoo 
He said, that there were some tests about it, but they are commented on now. Can you provide a link, please?

Probably, the problem may be connected with a lot of commented code in `CheckpointCallback`. This code includes such keywords as `resume` and `resume_dir`.

**Comment by Scitator** [comment]
Dear @AlekseySh please prove the issue into the required form :) 
"Bug" should be okay ;)
Thanks in advance!
