### ISSUE TITLE
Catalyst docs

### ISSUE THREAD

**Issue by ditwoo** [catalyst-team/catalyst#1177]
## 🐛 Bug Report

Could you please fix the link to previous versions of docs.

![image](https://user-images.githubusercontent.com/7264490/114912151-58c33280-9e28-11eb-8538-0a445be5cd70.png)

### Environment
Please copy and paste the output from our environment collection script
```bash
catalyst-contrib --collect-env
# or manually
wget https://raw.githubusercontent.com/catalyst-team/catalyst/master/catalyst/contrib/scripts/collect_env.py
python collect_env.py
```
(or fill out the checklist below manually).

```bash
# example checklist, fill with your info
Catalyst version: 20.04.2
PyTorch version: 1.4.0
TensorFlow version: N/A
TensorBoard version: 2.2.1
OS: Mac OSX 10.15.4
Python version: 3.7
CUDA runtime version: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```

### Checklist
- [ ] bug description
- [ ] steps to reproduce
- [ ] expected behavior
- [ ] environment
- [ ] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [ ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [ ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [ ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Fixed ;)
https://catalyst-team.github.io/catalyst/versions.html
