### ISSUE TITLE
Return `resume` support for CheckpointCallback and `.train`, `predict`

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#1193]
## 🚀 Feature Request

Return the resume support for the [`CheckpointCallback`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/callbacks/checkpoint.py#L374#L393) and [`Runner.train`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/runner.py#L315#L352), [`Runner.predict`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/runner.py#L535#L546).

### Motivation

That would be a great user-friendly feature – resume is quite common task during deep learning development.

### Proposal

1. Uncommen the [CheckpointCallback code](https://github.com/catalyst-team/catalyst/blob/master/catalyst/callbacks/checkpoint.py#L609#L646) and check its correctness.... from my perspective, it should be refactored a bit.
2. Add its support to [Runner](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/runner.py#L306#L313).
3. Uncomment the [cli interface](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/scripts/run.py#L35) and update the [ConfigRunner](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/config.py#L408) and [HydraRunner](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/hydra.py#L372).

Proposed use case:
```python
import os
from torch import nn, optim
from torch.utils.data import DataLoader
from catalyst import dl, utils
from catalyst.data.transforms import ToTensor
from catalyst.contrib.datasets import MNIST

model = nn.Sequential(nn.Flatten(), nn.Linear(28 * 28, 10))
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.02)

loaders = {
    "train": DataLoader(
        MNIST(os.getcwd(), train=True, download=True, transform=ToTensor()), batch_size=32
    ),
    "valid": DataLoader(
        MNIST(os.getcwd(), train=False, download=True, transform=ToTensor()), batch_size=32
    ),
}

runner = dl.SupervisedRunner(
    input_key="features", output_key="logits", target_key="targets", loss_key="loss"
)
# model training
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    loaders=loaders,
    num_epochs=1,
    callbacks=[
        dl.AccuracyCallback(input_key="logits", target_key="targets", topk_args=(1, 3, 5)),
        dl.PrecisionRecallF1SupportCallback(
            input_key="logits", target_key="targets", num_classes=10
        ),
        dl.AUCCallback(input_key="logits", target_key="targets"),
        # catalyst[ml] required ``pip install catalyst[ml]``
        # dl.ConfusionMatrixCallback(input_key="logits", target_key="targets", num_classes=10),
    ],
    logdir="./logs",
    valid_loader="valid",
    valid_metric="loss",
    minimize_valid_metric=True,
    verbose=True,
    load_best_on_end=True,
)

# here is the trick
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    loaders=loaders,
    num_epochs=1,
    callbacks=[
        dl.AccuracyCallback(input_key="logits", target_key="targets", topk_args=(1, 3, 5)),
        dl.PrecisionRecallF1SupportCallback(
            input_key="logits", target_key="targets", num_classes=10
        ),
        dl.AUCCallback(input_key="logits", target_key="targets"),
        # catalyst[ml] required ``pip install catalyst[ml]``
        # dl.ConfusionMatrixCallback(input_key="logits", target_key="targets", num_classes=10),
    ],
    # ----
    logdir="./logs2",
    resume="./logs/checkpoints/train.1.pth",
    # ----
    valid_loader="valid",
    valid_metric="loss",
    minimize_valid_metric=True,
    verbose=True,
    load_best_on_end=True,
)
```

### Checklist
- [x] feature proposal description
- [x] motivation
- [x] extra proposal context / proposal alternatives review
  

### FAQ
Please review the FAQ before submitting an issue:
- [x] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
we need it 👀

**Comment by Nimrais** [comment]
Hi there! Is anyone working on this?

**Comment by Scitator** [comment]
@y-ksenia?

**Comment by y-ksenia** [comment]
Yes, just started

**Comment by Podidiving** [comment]
Is this task done?

**Comment by Scitator** [comment]
nope, still waiting 👀

**Comment by Scitator** [comment]
👀

**Comment by y-ksenia** [comment]
We can close it, I guess 🥳
