### ISSUE TITLE
Add torch metrics support

### ISSUE THREAD

**Issue by bagxi** [catalyst-team/catalyst#1195]
## 🐛 Bug Report

[`AdditiveValueMetric`](https://github.com/catalyst-team/catalyst/blob/3db5d21a01ab9a138bc76a26b8ca97870922f3f2/catalyst/metrics/_additive.py#L62) assumes that the metric value can be converted to float / NumPy array. But in reality, there are many cases when it is much faster and easier to calculate metrics on GPU using PyTorch. And this will cause errors as `torch.Tensor` cannot be converted to NumPy automatically.

### How To Reproduce
1. Use `FunctionalMetricCallback` with any metric function that returns `torch.Tensor` e.g. [`piq.psnr`](https://github.com/photosynthesis-team/piq/blob/master/piq/psnr.py#L9)

 

#### Code sample

https://github.com/leverxgroup/esrgan/blob/update-catalyst/esrgan/callbacks/metrics.py#L20

### Expected behavior

It would be great if `utils.detach_tensor` was used before metrics averaging.

### Environment
Please copy and paste the output from our environment collection script
```bash
catalyst-contrib --collect-env
# or manually
wget https://raw.githubusercontent.com/catalyst-team/catalyst/master/catalyst/contrib/scripts/collect_env.py
python collect_env.py
```
(or fill out the checklist below manually).

```bash
# example checklist, fill with your info
Catalyst version: 20.04.2
PyTorch version: 1.8.0
TensorFlow version: N/A
TensorBoard version: 2.2.1
OS: Ubuntu 20.04 LTS
Python version: 3.8
CUDA runtime version: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```

### Checklist
- [x] bug description
- [x] steps to reproduce
- [x] expected behavior
- [x] environment
- [x] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [x] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Nice catch!
Do you think adding `mode=["numpy", "torch"]` would be a good idea for AdditiveValueMetric?

**Comment by bagxi** [comment]
I think it will be easier to check types of inputs and use `utils.detach_tensor` in case of torch tensors?

**Comment by Scitator** [comment]
why you could not specify that during init? 
checking `dtype` each batch looks like performance killer

**Comment by bagxi** [comment]
Sometimes people may have no ideas about types. And it also will be much easier to use this thing.

Can we assume that `dtype` of each batch is the same? If yes, then we can check `dtype` only for the first batch and store this information inside `AdditiveValueMetric`.

**Comment by Scitator** [comment]
the problem here is that it requires you to check the type **each** batch, which is some kind of slow
moreover... how could we do not know the dtype of the returned metric value? it should be documented, I hope

**Comment by bagxi** [comment]
And what about the function that will redefine itself on the first batch? In this case, `dtype` will be checked only once, but it is a little bit tricky approach.

**Comment by Scitator** [comment]
🤔  do you have an example of such a function?

**Comment by bagxi** [comment]
```python
class Metric:
    # ...

    def update(self, value, ...):
        self.value = self.compute_wrapper(value)
        # ...

    def compute_wrapper(self, value):
        if torch.is_tensor(value):
            self.compute_wrapper = catalyst.utils.detach_tensor
        else:
            self.compute_wrapper = lambda x: x

    def compute(self):
        # ...
        return value
```

**Comment by Scitator** [comment]
why should we use such a metric with undefined behavior? do you have any real-metric examples?
