### ISSUE TITLE
Docs for checkpoints logic

### ISSUE THREAD

**Issue by gazay** [catalyst-team/catalyst#120]
Hey, great framework!

I can't find in docs and don't see from API how to easily change checkpointer behavior - which metric it should monitor for checkpoints, max/min etc.

And I'm not sure about checkpoints at all - where should I find saved models, what is the format, are they enabled by default, what is the logic for saving them right now. And can I customize all of that?

**Comment by Scitator** [comment]
Hi,

Docs updates are in WIP mode for now, nevertheless the API is quite strainforward. 
If you are using catalyst through notebook-interface, like [here](https://github.com/catalyst-team/catalyst/blob/master/examples/notebook-example.ipynb), all you need to specify are:
`main_metric` and `minimize_metric`. For example, in "Setup 4 - training with additional metrics" you can run

```python
# model training
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    loaders=loaders,
    callbacks=[
        PrecisionCallback(),
        EarlyStoppingCallback(patience=2, min_delta=0.01)
    ],
    logdir=logdir,
    n_epochs=n_epochs,
    main_metric="precision01", # "precision03" or "precision05"
    minimize_metric=False,
    verbose=True
)
```
and checkpointer will save model based on "precision01" (aka accuracy) metric. 
By default, `SupervisedRunner` (and `SupervisedExperiment`) have checkpointer turned on during train stage.

If you are using config-interface, like [here](https://github.com/catalyst-team/catalyst/tree/master/examples/cifar_stages), all you need to do - specify `state_params` [here](https://github.com/catalyst-team/catalyst/blob/master/examples/cifar_stages/config.yml#L18): `main_metric` and `minimize_metric` again.

All the experiment checkpoints are located at `{your_logdir}/checkpoints/*`. By default, catalyst additionally saves best checkpoint (based on chosen metric) - `best.pth` and last one - `last.pth`.

FYI, source code for `train` method is [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiments/runner.py#L237) and checkpointer logic through  `CheckpointCallback` is [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/base.py#L12).

**Comment by gazay** [comment]
Awesome, thank you!
