### ISSUE TITLE
import catalyst.core.callbacks.metrics is not regonized

### ISSUE THREAD

**Issue by MordehayM** [catalyst-team/catalyst#1212]
I tried to import the class - MetricCallback but didn't succeed.
 import catalyst.core.callbacks.metrics is not regonized
But in the docs there is that class: 
https://catalyst-team.github.io/catalyst/v20.04.1/api/core.html?highlight=catalyst%20core%20callbacks%20metrics#module-catalyst.core.callbacks.metrics

Help please

**Comment by Scitator** [comment]
could you please use the [`21.04.1` version](https://catalyst-team.github.io/catalyst/v21.04.2/index.html)?
