### ISSUE TITLE
Verbose=True prints all Iteration progress

### ISSUE THREAD

**Issue by jaideep11061982** [catalyst-team/catalyst#1213]
Verbose =True prints in all iteration progress rather than regular tqdm progress that dsnt prints all iterations , just updates as iteration progresses and then next epoch in next line.

**Comment by broniyasinnik** [comment]
It seems that also when setting verbose=False it still prints the whole progress in the console.

**Comment by Scitator** [comment]
Sorry, no question found, closing the issue.
