### ISSUE TITLE
Segmentation tutorial

### ISSUE THREAD

**Issue by sayakpaul** [catalyst-team/catalyst#1227]
Was wondering where the segmentation notebook go? The full link is:

https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb.

**Comment by Scitator** [comment]
Hi, have you tried out our [minimal examples](https://github.com/catalyst-team/catalyst#minimal-examples)? There is CV - MNIST segmentation example available.
