### ISSUE TITLE
Accessing model/Runner inside catalyst.dl.Logger

### ISSUE THREAD

**Issue by benihime91** [catalyst-team/catalyst#1233]
Hi, I have recently started using Catalyst and I must say It is quite awesome. Bing thanks to the contributors. So I had a question. Is there a way I can access the `runner`/ `model` inside a `catalyst.dl.Logger` instance. 

So what I am specifically trying to achieve is logging my `model graph` to `wandb`. For that I need to access the `model`. I have already pathched the existing wandb logger to achieve more functionality such as `grouping`, etc.. 

Is it possible to access either the model or the runner inside the logger ? 

My patched wandb logger >>>

```python
class CustomWandbLogger(dl.WandbLogger):
    """A wrapper over catalyst.dl.WandbLogger"""
    def __init__(self, project, name=None, entity=None, params=None):
        self.project = project
        self.name = name
        self.entity = entity
        self.run = wandb.init(project=self.project, name=self.name, entity=self.entity, allow_val_change=True, **params)
        
    def close_log(self): pass
```

**Comment by Scitator** [comment]
Hi,
Logger API tries to create standalone logging.... API 😂 , so there are no connections with the Runner class.
I think you just need `log_model` method for the Logger API. For example, during [Neptune integration](https://github.com/catalyst-team/catalyst/pull/1196/files) we have added `log_artifact` one. 
It would be great if you are ready to contribute to the project (+ it would be great to add `log_model` to the TensorboardLogger too, but it's another Pull Request).

Will it work for you, what do you think?

**Comment by benihime91** [comment]
Yes. `log_model` definitely works ... Thanks a lot for the prompt reply ! Can I work on adding a `log_model` for `WandbLogger` in the upcoming days, preferably next week. I plan on getting myself familier with the API in the meantime
