### ISSUE TITLE
Incorrect md5 sums in Imagenette and Imagewoof from `catalyst.contrib.datasets`

### ISSUE THREAD

**Issue by NetherQuartz** [catalyst-team/catalyst#1265]
## 🐛 Bug Report
It's impossible to use Imagenette or Imagewoof because of incorrect md5 sums in the code.

### How To Reproduce
1. Import `catalyst.contrib.datasets`
1. Instantiate Imagenette, Imagenette160, Imagenette320, Imagewoof, Imagewoof160 or Imagewoof320 with `download=True`
3. Get `RuntimeError: File not found or corrupted` after download

 

#### Code sample
```Python
from catalyst.contrib.datasets import Imagenette160


Imagenette160(".", download=True)  # RuntimeError: File not found or corrupted
```

### Expected behavior
The datasets are being downloaded with no errors.

### Environment

```bash
Collecting environment information...
Catalyst version: 21.06
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2
TensorFlow version: N/A
TensorBoard version: N/A

OS: Ubuntu 20.04.2 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] catalyst==21.6
[pip3] numpy==1.19.1
[pip3] tensorboardX==2.2
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

```

### Checklist
- [X] bug description
- [X] steps to reproduce
- [X] expected behavior
- [X] environment
- [X] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [X] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [X] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [X] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [X] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [X] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Hi, good catch, thanks for the issue!
Looks like we need to backup the data :)

**Comment by Scitator** [comment]
It would be great if you could bugfix with the updated links from https://github.com/fastai/imagenette

**Comment by NetherQuartz** [comment]
Sure, will do this ASAP

P.S. Maybe, you should host datasets in your own location and store checksums somewhere near to files rather than in code…

**Comment by Scitator** [comment]
yup, 
> Looks like we need to backup the data :)

**Comment by Scitator** [comment]
should be fixed in master and future releases :)
