### ISSUE TITLE
Matplotlib backend automatically set as 'Agg' when Catalyst is imported.

### ISSUE THREAD

**Issue by jyuan-dev** [catalyst-team/catalyst#1270]
## 🐛 Bug Report

https://github.com/catalyst-team/catalyst/blob/93774200bc65f5c5ee7e2ad9935fee901c277be0/catalyst/contrib/utils/visualization.py#L6

`matplotlib.use("Agg")` set the backend of catalyst to `agg`, which requires user to click to close the visualization window. I think it would be better if it is kept in original matplotlib backend.

please make a test before allowing the pull request.

### How To Reproduce
1. run first script, in PyCharm with Catalyst installed Env.
2. run second script, in PyCharm with Catalyst installed Env.
3. make comparison

 

#### Code sample

```
import numpy as np
import matplotlib.pyplot as plt
image = np.random.random([800,800,3]) * 255.0
plt.imshow(image)
plt.show()
```

```

from catalyst import dl, utils
from catalyst.data import ToTensor
from catalyst.contrib.datasets import MNIST

import numpy as np
import matplotlib.pyplot as plt
image = np.random.random([800,800,3]) * 255.0
plt.imshow(image)
plt.show()
```

### Expected behavior

In pycharm, it supposed that the image should pop up in the SciView window, but after importing catalyst packages, it doesn't appear, after commenting the `matplotlib.use("Agg")`, unexceptional behavior disappeared.

### Checklist
- [ x ] bug description
- [ x ] steps to reproduce
- [ x ] expected behavior
- [ x ] environment
- [ x ] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [ x ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [ x ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ x ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Nice catch!
Could you please check the performance with such a hotfix:
```python
import torch
from torch.utils.data import DataLoader, TensorDataset
from catalyst import dl

# sample data
num_samples, num_features, num_classes = int(1e4), int(1e1), 4
X = torch.rand(num_samples, num_features)
y = (torch.rand(num_samples,) * num_classes).to(torch.int64)

# pytorch loaders
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=32, num_workers=1)
loaders = {"train": loader, "valid": loader}

# model, criterion, optimizer, scheduler
model = torch.nn.Linear(num_features, num_classes)
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters())
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, [2])

# model training
runner = dl.SupervisedRunner(
    input_key="features", output_key="logits", target_key="targets", loss_key="loss"
)
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    loaders=loaders,
    logdir="./logdir",
    num_epochs=3,
    valid_loader="valid",
    valid_metric="accuracy03",
    minimize_valid_metric=False,
    verbose=True,
    callbacks=[
        dl.AccuracyCallback(
            input_key="logits", target_key="targets", num_classes=num_classes
        ),
        dl.PrecisionRecallF1SupportCallback(
            input_key="logits", target_key="targets", num_classes=num_classes
        ),
        dl.AUCCallback(input_key="logits", target_key="targets"),
        dl.ConfusionMatrixCallback(
            input_key="logits", target_key="targets", num_classes=num_classes
        ),
    ],
)
```

**Comment by jyuan-dev** [comment]
time to run the given script without agg backend: 30.802659034729004s, 29.775018453598022s, 30.18287754058838s
time to run the given script with agg backend: 29.499370336532593s, 29.99454355239868s, 29.327373027801514s

generally, there is no performance sacrifice without agg backend in my opinion.

**Comment by Scitator** [comment]
🤔  could you please create a PR with hotfi?

**Comment by Scitator** [comment]
btw, are the ConfusionMatrix plots in the tensorboard correct with the hotfix?

**Comment by jyuan-dev** [comment]
![image](https://user-images.githubusercontent.com/29662741/128243269-912bd08c-f0c4-4d5c-a240-9ce05b1e6525.png)
focusing only on plotting, I think it is right. An PR is already made, but not sure if it is hotfix or not.

**Comment by jyuan-dev** [comment]
As MR is already done, This issue is closed now
