### ISSUE TITLE
Support for Comet Logger

### ISSUE THREAD

**Issue by DN6** [catalyst-team/catalyst#1281]
## 🚀 Feature Request
I would like to add support for a [Comet ML](https://www.comet.ml/site/data-scientists/) Logger to Catalyst 

### Motivation
Comet provides a suite of logging and visualization options that makes it easy for practitioners to analyze, visualize and share the results of their model development process. I think it would work very well with Catalyst's focus on reproducibility, rapid experimentation, and codebase reuse. 

### Proposal
The integration would follow a similar pattern to previous ones such as MLFlow, Neptune, and WandB. The workflow would look something like 

```
import comet_ml
import torch
from torch.utils.data import DataLoader, TensorDataset
from catalyst import dl
from catalyst.loggers.comet import CometLogger

# data
num_samples, num_features = int(1e4), int(1e1)
X, y = torch.rand(num_samples, num_features), torch.rand(num_samples)
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=32, num_workers=1)
loaders = {"train": loader, "valid": loader}

# model, criterion, optimizer, scheduler
model = torch.nn.Linear(num_features, 1)
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters())
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, [3, 6])
logger = CometLogger()

# model training
runner = dl.SupervisedRunner()
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    loaders=loaders,
    logdir="./logdir",
    valid_loader="valid",
    valid_metric="loss",
    minimize_valid_metric=True,
    num_epochs=8,
    verbose=True,
    loggers={"comet": logger},
)
```

### Alternatives
Did not consider alternatives for this specific proposal, as this enhancement is to help Comet users log data from Catalyst. 

### Checklist
- [x] feature proposal description
- [x] motivation
- [x] extra proposal context / proposal alternatives review
  

### FAQ
Please review the FAQ before submitting an issue:
- [x] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Hi, that sounds great!
Do you need any help with the implementation?

**Comment by DN6** [comment]
Hi, @Scitator, one of our engineers has something in the works. We're just testing and running through the Catalyst checklist for creating a PR to make sure we don't miss anything. We can open a PR within the next couple of days if that's okay?

**Comment by Scitator** [comment]
Sure, thank you!

**Comment by DN6** [comment]
Hi @Scitator. Thanks for merging in the PR! Regarding including a tutorial notebook for the README, is it alright for me to open a separate PR for that?

**Comment by Scitator** [comment]
Yup, that would be okay, thanks!
