### ISSUE TITLE
WandB batch metrics logging error

### ISSUE THREAD

**Issue by ivan-chai** [catalyst-team/catalyst#1290]
## 🐛 Bug Report
In wandb all batch metrics are logged as single value per epoch.

### Expected behavior
Batch metrics must be logged once per step.

```bash
Catalyst version: 21.7
```

### Additional context
The problem is here:

https://github.com/catalyst-team/catalyst/blob/master/catalyst/loggers/wandb.py#L115

Step must be equal to global_sample_step, not global_epoch_step.

**Comment by Scitator** [comment]
maybe, @AyushExel could help 👀

**Comment by AyushExel** [comment]
- @Scitator I'm out on a vacation. I'll have a look at this on monday. But it sounds like we might not have a good solution for this as W&B only has one global step.

**Comment by AyushExel** [comment]
@ivan-chai I remember working on this. the reason that the batch metrics are also logged on epoch level is that W&B supports 1 global step and you cannot edit or log at previous steps, so I decided to log everything on epoch level. There are other methods that will end up dropping data if any previous step is encountered.

**Comment by ivan-chai** [comment]
Thank you for your response! May be it is better to always log sample_step?

**Comment by Scitator** [comment]
yeah, I think, we could just use `global_sample_step` as a wandb step for all `.log`

**Comment by AyushExel** [comment]
@Scitator @ivan-chai Is the `global_sample_step` strictly increaseing? If it is, then yes we can use that

**Comment by Scitator** [comment]
Yes ;)
let's use it

**Comment by Scitator** [comment]
@AyushExel could you please drop a PR with such a small hotfix?
we are going to release `21.09` version soon ;)

**Comment by AyushExel** [comment]
@Scitator sounds good. I'll do it within 2 days

**Comment by AyushExel** [comment]
@Scitator I'm working on it now. I noticed that the logger API now supports artifacts as well. I'll add that too. I just need a bit of clarification on the usage. 
```
    def log_artifact(
        self,
        tag: str,
        artifact: object = None,
        path_to_artifact: str = None,
```
here, `artifact: object` is an identifier for the artifact right? Or it can be an in-memory object? 
I saw this example usage [here](https://github.com/catalyst-team/catalyst/blob/e1d78b7dd568c4d5cd94be417d6d8b93ef27b2e5/catalyst/callbacks/profiler.py#L177)

**Comment by Scitator** [comment]
yup, looks like so
```
artifact: object = None,  - in-memory object
path_to_artifact: str = None, - on-disk object
```
here is another example - https://github.com/catalyst-team/catalyst/blob/e1d78b7dd568c4d5cd94be417d6d8b93ef27b2e5/catalyst/loggers/neptune.py#L281

**Comment by Scitator** [comment]
btw, @ditwoo why do we use the profiler in such a way? 😂

**Comment by AyushExel** [comment]
@Scitator in the 2nd example that you linked, it'll raise exception if both `artifact` and `oath_to_artifact` is not None. But in the profiler example, both of them are not None so it'll raise an exception. Is this an intended use case? 
More specifically, how'd you preferred handling the cases when both of the arguments are set?

**Comment by Scitator** [comment]
@AyushExel yes, and I think it's correct behavior. 
The profiler case looks a bit strange in such a case and I think, it's a little bug 😅 
@ditwoo could you please help with the profiler initial logic?

**Comment by AyushExel** [comment]
Okay, thanks for the clarification. I'll update the logger with the intended artifacts use case.

**Comment by AyushExel** [comment]
@Scitator I have fixed this and added artifacts support. Can you provide an example training script using catalyst trainer which log artifacts? I want to check all the use cases before submitting the PR. Sorry, I couldn't find something relevant in the quickstart section of docs.

**Comment by Scitator** [comment]
@AyushExel could you please use https://github.com/neptune-ai/examples/blob/main/integrations-and-supported-tools/catalyst/scripts/Neptune_Catalyst_more_options.py ?

**Comment by Scitator** [comment]
btw, we are going to release another version tomorrow, so, the fix would truly welcome ;)

**Comment by AyushExel** [comment]
Just running tests. PR coming soon
