### ISSUE TITLE
Redundant pooling layers

### ISSUE THREAD

**Issue by lext** [catalyst-team/catalyst#13]
Global pooling layers are already easy to implement using adaptive pooling in pytorch: https://pytorch.org/docs/stable/nn.html#pooling-layers, so they can be removed from e.g.

https://github.com/Scitator/catalyst/blob/e55719e74717754c79d190e1aeeb6335bee24402/modules/pooling.py#L16

**Comment by Scitator** [comment]
You are right, they are already in PyTorch. 
Nevertheless, there was an issue with their ONNX support (https://github.com/pytorch/pytorch/issues/5310).

This modules definitely should be replaced after full PyTorch support. But for now, it's better to keep them for compatibility.

**Comment by buriy** [comment]
@Scitator You might put a comment with this explanation in the definition of this class.
