### ISSUE TITLE
[feature] OneCycle general schduler

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#133]
idea:
- assume we have training stage process 0.0 -> 1.0
- on 0 -> {warm_fraction}, increase lr from `init_lr` to `max_lr`
- on {warm_fraction} -> {cool_fraction}, use linear/cosine decay from `max_lr` to `min_lr`
- on {cool_fraction} -> 1.0, use `min_lr`
- `batch` or `epoch` lr schduling

the same thing with momentum

**Comment by TezRomacH** [comment]
done on https://github.com/catalyst-team/catalyst/pull/162
