### ISSUE TITLE
catalys.contrib.nn.modules.LAMA: "mask" parameter not used

### ISSUE THREAD

**Issue by lainisourgod** [catalyst-team/catalyst#1332]
## 🐛 Bug report

1. In [TemporalDropLastWrapper](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/nn/modules/lama.py#L123). Any layer wrapped with this one will not get mask. I guess it should just move mask into net with `x_out = self.net(x, mask)`. Also I guess `drop last` means drop output of `net` so ` x = x[:, :-1, :]` should go after `net(x, mask)`.
2. In [TemporalAttentionPooling](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/nn/modules/lama.py#L65-L84): `mask` parameter not used at all so code works incorrectly by not removing PAD values from input.

**Comment by Scitator** [comment]
🤔  nice catch, it may be so! that's why this is contib :)
It would be great if could contribute a hotfix for this part 🚀
