### ISSUE TITLE
[fix] fix registry exception for duplicate factory

### ISSUE THREAD

**Issue by Scitator** [catalyst-team/catalyst#135]
@TODO:
- return exception for duplicate factory
- check that all registries usage are correct: both in `__init__.py` and `model.py` for example

**Comment by hexfaker** [comment]
Bug was caused by relative import implementation in python. Module code can be executed twice. So smart check was implemented. Now we compare factories on name duplication, and raise error only if factories are not the same.

**Comment by hexfaker** [comment]
The image showing double module execution stacktraces diff
![image](https://user-images.githubusercontent.com/4684868/56461597-31af0300-63be-11e9-9c2c-22ffe5f9f4e7.png)
