### ISSUE TITLE
Metrics calculation is going much slower compared with version 21.07 in semantic segmentation task

### ISSUE THREAD

**Issue by jyuan-dev** [catalyst-team/catalyst#1351]
## 🐛 Bug Report
Bug unknown, 

However, on version 21.07 training speed arrives 14 iter/s in my GPU, but only 2 iter/s on version 21.10 

### How To Reproduce
please find a simple semantic segmentation script, and i can run it and give you feedbacks.

### Expected behavior
training is much slower compared with 21.07

### Checklist
- [X] bug description
- [ ] steps to reproduce
- [X] expected behavior
- [ ] environment
- [ ] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [ ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [ ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [ ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
could you please provide colab examples?

**Comment by jyuan-dev** [comment]
Sorry, I am too busy recently, I will not have time before end of this year, I think you can run it on the segmentation example of catalyst then compare the efficiency difference
