### ISSUE TITLE
A question in CV - MNIST segmentation example

### ISSUE THREAD

**Issue by fjd330621** [catalyst-team/catalyst#1389]
I'm new to this, so please forgive me if the question is silly.
I'm a little confused about the last code in this short paragraph that why the self._target_key is also the x rather than y or maybe batch["targets"].
```
class CustomRunner(dl.SupervisedRunner):
    def handle_batch(self, batch):
        x = batch[self._input_key]
        x_noise = (x + torch.rand_like(x)).clamp_(0, 1)
        x_ = self.model(x_noise)
        self.batch = {self._input_key: x, self._output_key: x_, self._target_key: x}
```

**Comment by Scitator** [comment]
hi,
🤔  this is a simple denoising segmentation example, so, there no `target` available
Nevertheless, you are right, it should be something like
```python
self.batch = {self._input_key: x_noise, self._output_key: x_, self._target_key: x}
```

**Comment by fjd330621** [comment]
Oh, oh, oh, I see. Thank you very much
