### ISSUE TITLE
Tensorboard Logger; Log weights and distributions.

### ISSUE THREAD

**Issue by alfieroddan** [catalyst-team/catalyst#1408]
## 🚀 Feature Request

Simply add a new function in the `TensorboardLogger(ILogger)` code that allows to add histograms to Tensorboard. This allows better logging in Tensorboard.

### Motivation
I often use the histogram in my deep learning projects and having this feature within the Tensorboard class will allow me to improve my logging in catalyst-dl. 

It is not particuarly hard to implement and I have provided the code below.

### Proposal
```
    def log_weights(
        self,
        runner: "IRunner",
    ) -> None:
        """Logs model weights to Tensorboard for current epoch."""
        assert runner.loader_key is not None
        # check saving weights is possible
        if 'named_parameters' in dir(runner.model):
            self._check_loader_key(loader_key=runner.loader_key)
            # log weights of model
            for name, params in runner.model.named_parameters():
                # save weights as histogram
                self.loggers[runner.loader_key].add_histogram(
                    tag=name, values=params, global_step=runner.epoch_step,\
                    bins='tensorflow'
                )
```

I call the above function in a custom callback:

```
class TbSave(dl.Callback):
    def __init__(self, input_key='features', log_weights=True):
        super().__init__(order=dl.CallbackOrder.External)
        # key of input to be saved
        self.input_key=input_key
        self.log_weights = log_weights
        self.train_batch = 1
        self.test_batch = 1

    def save_inputs(self, runner):
        """
        Save all the inputs as images,
        uses tensorboard. 
        """
        # train flag
        train = runner.is_train_loader
        # save from train flag
        if train:
            tag = 'train/' + str(self.train_batch)
        else:
            tag = 'test/' + str(self.test_batch)
        # get images from key
        images = runner.batch[self.input_key]
        # make grid of batch, # permute (CHW) -> (HWC)
        grid = torchvision.utils.make_grid(images).permute(1, 2, 0).numpy()
        # log the image
        runner.loggers['tb2'].log_image(runner=runner, image=grid, tag=tag)

    def on_epoch_end(self, runner):
        """
        On epoch end.
        """
        assert 'tb2' in runner.loggers.keys()
        # reset batch
        self.train_batch = 1
        self.test_batch = 1
        # save weights of model
        runner.loggers['tb2'].log_weights(runner=runner)

    def on_batch_end(self, runner):
        """
        On batch end.
        Input: runner
        """
        assert 'tb2' in runner.loggers.keys()
        # record inputs and outputs on first epoch
        if (runner.epoch_step == 1) and ('tb2' in runner.loggers.keys()):
            self.save_inputs(runner)
        # + batch for tags to save
        if runner.is_train_loader:
            self.train_batch += 1
        else:
            self.test_batch += 1
```

However this implementation would be greatly simplified by having the function within the logger class. That way I do not need to ensure `assert 'tb2' in runner.loggers.keys()`.

### Alternatives
I considered using a new custom logger but this did not integrate with other loggers and Tensorboard's file compression massively saves space.

### Additional context
Here is what the output looks like:
<img width="1432" alt="Screenshot 2022-03-04 at 10 58 16" src="https://user-images.githubusercontent.com/51797647/156751244-9f6a8a49-dc7d-4b79-90d7-f612ad33f829.png">

### Checklist
- [x ] feature proposal description
- [ x] motivation
- [ x] extra proposal context / proposal alternatives review
  

### FAQ
Please review the FAQ before submitting an issue:
- [x ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Hi, the feature looks cool! 💪 
Are you interested in implementation? 
Do you have proposals on where should it be integrated for SupervisedRunner (for example)?

**Comment by alfieroddan** [comment]
Currently I use a custom Tensorboard class called `TensorboardLogger2`. 

I think keeping it as a function within the Logger class is fine since the tensorboard logger is called by default anyway. You could put it within the `log_metrics` function instead of the supervised runner? The issue would be defining the scope for the weights.

Personally I would just like it to be within the Tensorboard Class so I can call it with a custom callback.

`class TensorboardLogger2(ILogger):
    """Tensorboard logger for parameters, metrics, images and other artifacts.

    Args:
        logdir: path to logdir for tensorboard.
        use_logdir_postfix: boolean flag
            to use extra ``tensorboard`` prefix in the logdir.
        log_batch_metrics: boolean flag to log batch metrics
            (default: SETTINGS.log_batch_metrics or False).
        log_epoch_metrics: boolean flag to log epoch metrics
            (default: SETTINGS.log_epoch_metrics or True).

    .. note::
        This logger is used by default by ``dl.Runner`` and ``dl.SupervisedRunner``
        in case of specified logdir during ``runner.train(..., logdir=/path/to/logdir)``.

    Examples:

    .. code-block:: python

        from catalyst import dl

        runner = dl.SupervisedRunner()
        runner.train(
            ...,
            loggers={"tensorboard": dl.TensorboardLogger(logdir="./logdir/tensorboard"}
        )

    .. code-block:: python

        from catalyst import dl

        class CustomRunner(dl.IRunner):
            # ...

            def get_loggers(self):
                return {
                    "console": dl.ConsoleLogger(),
                    "tensorboard": dl.TensorboardLogger(logdir="./logdir/tensorboard")
                }

            # ...

        runner = CustomRunner().run()
    """

    def __init__(
        self,
        logdir: str,
        use_logdir_postfix: bool = False,
        log_batch_metrics: bool = SETTINGS.log_batch_metrics,
        log_epoch_metrics: bool = SETTINGS.log_epoch_metrics,
    ):
        """Init."""
        super().__init__(
            log_batch_metrics=log_batch_metrics, log_epoch_metrics=log_epoch_metrics
        )
        if use_logdir_postfix:
            logdir = os.path.join(logdir, "tensorboard")
        self.logdir = logdir
        self.loggers = {}
        os.makedirs(self.logdir, exist_ok=True)

    @property
    def logger(self):
        """Internal logger/experiment/etc. from the monitoring system."""
        return self.loggers

    def _check_loader_key(self, loader_key: str):
        if loader_key not in self.loggers.keys():
            logdir = os.path.join(self.logdir, f"{loader_key}")
            self.loggers[loader_key] = SummaryWriter(logdir)

    def _log_metrics(
        self, metrics: Dict[str, float], step: int, loader_key: str, suffix=""
    ):
        for key, value in metrics.items():
            self.loggers[loader_key].add_scalar(f"{key}{suffix}", float(value), step)

    def log_image(
        self,
        tag: str,
        image: np.ndarray,
        runner: "IRunner",
        scope: str = None,
    ) -> None:
        """Logs image to Tensorboard for current scope on current step."""
        assert runner.loader_key is not None
        self._check_loader_key(loader_key=runner.loader_key)
        tensor = _image_to_tensor(image)
        self.loggers[runner.loader_key].add_image(
            f"{tag}", tensor, global_step=runner.epoch_step
        )

    def log_weights(
        self,
        runner: "IRunner",
    ) -> None:
        """Logs model weights to Tensorboard for current epoch."""
        assert runner.loader_key is not None
        # check saving weights is possible
        if 'named_parameters' in dir(runner.model):
            self._check_loader_key(loader_key=runner.loader_key)
            # log weights of model
            for name, params in runner.model.named_parameters():
                # save weights as histogram
                self.loggers[runner.loader_key].add_histogram(
                    tag=name, values=params, global_step=runner.epoch_step,\
                    bins='tensorflow'
                )

    def log_metrics(
        self,
        metrics: Dict[str, float],
        scope: str,
        runner: "IRunner",
    ) -> None:
        """Logs batch and epoch metrics to Tensorboard."""
        if scope == "batch" and self.log_batch_metrics:
            self._check_loader_key(loader_key=runner.loader_key)
            # metrics = {k: float(v) for k, v in metrics.items()}
            self._log_metrics(
                metrics=metrics,
                step=runner.sample_step,
                loader_key=runner.loader_key,
                suffix="/batch",
            )
        elif scope == "loader" and self.log_epoch_metrics:
            self._check_loader_key(loader_key=runner.loader_key)
            self._log_metrics(
                metrics=metrics,
                step=runner.epoch_step,
                loader_key=runner.loader_key,
                suffix="/epoch",
            )
        elif scope == "epoch" and self.log_epoch_metrics:
            # @TODO: remove naming magic
            loader_key = "_epoch_"
            per_loader_metrics = metrics[loader_key]
            self._check_loader_key(loader_key=loader_key)
            self._log_metrics(
                metrics=per_loader_metrics,
                step=runner.epoch_step,
                loader_key=loader_key,
                suffix="/epoch",
            )

    def flush_log(self) -> None:
        """Flushes the loggers."""
        for logger in self.loggers.values():
            logger.flush()

    def close_log(self) -> None:
        """Closes the loggers."""
        for logger in self.loggers.values():
            logger.close()`

**Comment by Scitator** [comment]
As for me, if it's just for custom callback purposes - it's fine to keep it just as an extension of the current TensorboardLogger :)
Nevertheless, if you could propose a general way to log model weights at the end of each epoch (or some general setup), we could easily integrate it into the codebase. Especially if it's a general setup for other loggers.

FYI @AyushExel @jakubczakon

**Comment by AyushExel** [comment]
@Scitator hey, is there something to be done in the wandblogger's side?

**Comment by Scitator** [comment]
@AyushExel could we update the logger to support model weights logging also?

**Comment by AyushExel** [comment]
@Scitator logging artifacts is already supported by the wandbLogger right?

**Comment by Scitator** [comment]
yes!

**Comment by alfieroddan** [comment]
> As for me, if it's just for custom callback purposes - it's fine to keep it just as an extension of the current TensorboardLogger :) Nevertheless, if you could propose a general way to log model weights at the end of each epoch (or some general setup), we could easily integrate it into the codebase. Especially if it's a general setup for other loggers.
> 
> FYI @AyushExel @jakubczakon

Yep, here is my proposal (I only did tensorboard):


In catalyst/catalyst/core/runner.py:

  In class IRunner(ICallback, ILogger, ABC):
```
      def log_weights(self, *args, **kwargs) -> None:
          """Logs model weights if available to available loggers."""
            for logger in self.loggers.values():
                if 'log_weights' in dir(logger):
                    logger.log_weights(*args, **kwargs, runner=self)
```

In IRunner.on_epoch_end(self, runner: "IRunner")
```
    def on_epoch_end(self, runner: "IRunner"):
        """Event handler."""
        self.log_metrics(metrics=self.epoch_metrics, scope="epoch")
        self.log_weights()
        self.experiment_metrics[self.epoch_step] = self.epoch_metrics.copy()
        self.flush_log()
```

In catalyst/catalyst/loggers/ensorboard.py:

  In TensorboardLogger(ILogger):
  
    ```
        def log_weights(
            self,
            runner: "IRunner",
        ) -> None:
            """Logs model weights to Tensorboard for current epoch."""
            assert runner.loader_key is not None
            # check saving weights is possible
            if 'named_parameters' in dir(runner.model):
                self._check_loader_key(loader_key=runner.loader_key)
                # log weights of model
                for name, params in runner.model.named_parameters():
                    # save weights as histogram
                    self.loggers[runner.loader_key].add_histogram(
                        tag=name, values=params, global_step=runner.epoch_step,\
                        bins='tensorflow'
                    )
    ```

I think it would be as easy as that?

The runner class holds the model and epoch number, so each logger can easily add a histogram with those values. I am unsure how to log model weights from scikit-learn so that could be a problem?

It would probably be wise to add the self.log_weights() to experiment start as well. I am unsure how the engine works, so will leave that up to you guys.
