### ISSUE TITLE
Quick start 101 seems to need additional dependency

### ISSUE THREAD

**Issue by filipmu** [catalyst-team/catalyst#1415]
## 🐛 Bug Report
 
Following the Quick Start causes an error as written.  In step 2-
```from catalyst import dl, utils``` causes a module not found error.

### How To Reproduce
1. ```pip install  catalyst``` - I use miniconda and already have pytorch installed (v 1.11.0)
2.  In a jupyter notebook 
```
import os
from torch import nn, optim
from torch.utils.data import DataLoader
from catalyst import dl, utils
```

### Expected behavior

Import with no errors or please explain in Quick Start 101 what dependencies are needed - is `tensorboard` needed?

 

### Error Message
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [540], in <cell line: 4>()
      2 from torch import nn, optim
      3 from torch.utils.data import DataLoader
----> 4 from catalyst import dl, utils

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/catalyst/dl/__init__.py:3, in <module>
      1 # flake8: noqa
----> 3 from catalyst.core import *
      4 from catalyst.engines import *
      5 from catalyst.loggers import *

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/catalyst/core/__init__.py:8, in <module>
      1 # flake8: noqa
      2 # import order:
      3 # engine
      4 # runner
      5 # callback
      6 # logger
----> 8 from catalyst.core.engine import Engine
      9 from catalyst.core.runner import IRunner, IRunnerError
     10 from catalyst.core.callback import (
     11     ICallback,
     12     Callback,
   (...)
     18     CallbackWrapper,
     19 )

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/catalyst/core/engine.py:7, in <module>
      3 from typing import Callable, Dict
      5 import numpy as np
----> 7 from accelerate import Accelerator
      8 from accelerate.state import DistributedType
      9 import torch

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/accelerate/__init__.py:7, in <module>
      1 # flake8: noqa
      2 # There's no way to ignore "F401 '...' imported but unused" warnings in this
      3 # module, but to preserve other warnings. So, don't check this module at all.
      5 __version__ = "0.9.0"
----> 7 from .accelerator import Accelerator
      8 from .big_modeling import cpu_offload, disk_offload, dispatch_model, init_empty_weights, load_checkpoint_and_dispatch
      9 from .launchers import debug_launcher, notebook_launcher

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/accelerate/accelerator.py:32, in <module>
     30 from .scheduler import AcceleratedScheduler
     31 from .state import AcceleratorState
---> 32 from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
     33 from .utils import (
     34     DeepSpeedPlugin,
     35     DistributedDataParallelKwargs,
   (...)
     52     wait_for_everyone,
     53 )
     56 if is_deepspeed_available():

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/accelerate/tracking.py:29, in <module>
     26 _available_trackers = []
     28 if is_tensorboard_available():
---> 29     from torch.utils import tensorboard
     31     _available_trackers.append(LoggerType.TENSORBOARD)
     33 if is_wandb_available():

File /media/SSD/conda_env/gi-tract/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:1, in <module>
----> 1 import tensorboard
      2 from distutils.version import LooseVersion
      4 if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):

ModuleNotFoundError: No module named 'tensorboard'

```

### Environment
Please copy and paste the output from our environment collection script

Collecting environment information...
Catalyst version: 22.04
PyTorch version: 1.11.0
Is debug build: No
CUDA used to build PyTorch: 11.3
TensorFlow version: N/A
TensorBoard version: N/A

OS: Ubuntu 20.04.4 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CMake version: Could not collect

Python version: 3.10
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 470.129.06
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] catalyst==22.4
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.5
[pip3] segmentation-models-pytorch==0.2.1
[pip3] tensorboardX==2.5.1
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] catalyst                  22.4                     pypi_0    pypi
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] efficientnet-pytorch      0.6.3                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.21.5          py310hfa59a62_2  
[conda] numpy-base                1.21.5          py310h9585f30_2  
[conda] pytorch                   1.11.0          py3.10_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] segmentation-models-pytorch 0.2.1                    pypi_0    pypi
[conda] tensorboardx              2.5.1                    pypi_0    pypi
[conda] torchaudio                0.11.0              py310_cu113    pytorch
[conda] torchvision               0.12.0              py310_cu113    pytorch

### Checklist
- [X ] bug description
- [X ] steps to reproduce
- [X] expected behavior
- [X ] environment
- [ X] code sample / screenshots
  
### FAQ
Please review the FAQ before submitting an issue:
- [X] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [X] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [ ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by filipmu** [comment]
No worries - I am taking a different approach.

**Comment by Scitator** [comment]
Hi,
yeah, there could be some issue with accelerate internals and deps - we are already talking about them with accelerate team ;)

**Comment by YodaEmbedding** [comment]
Funnily, I was getting issues due to catalyst importing tensorboard (despite me not using tensorboard), but it turned out to be some `setuptools` regression https://github.com/pytorch/pytorch/issues/69894.
