### ISSUE TITLE
Add support for step based validation and checkpointing

### ISSUE THREAD

**Issue by julian-tonita** [catalyst-team/catalyst#1416]
## 🚀 Feature Request
The current library is built around epochs for a lot of core functionality including the checkpoint callback and validation metric functionality. It would be very useful to allow people to use steps instead of epochs to validate and save checkpoints.

### Motivation
For large datasets saving every epoch is pretty useless. Additionally, even for smaller datasets being able to run validation metrics more frequently can be very helpful to see how the model is performing.

### Proposal
For all core functionality that currently only uses epochs add a mode parameter which can be either epoch or step. If step is selected there will be another parameter num_steps (or something similarly named) which will control how many steps between the given functionality (e.g. steps between validation runs). Though I think this should be done for all epoch tied features the two most pressing are validation runs and checkpoints.

### Alternatives
It is likely possible to add this functionality with custom callbacks, but this seems like a lot of work especially given how common this request likely is.

### Checklist
- [x] feature proposal description
- [x] motivation
- [x] extra proposal context / proposal alternatives review
  

### FAQ
Please review the FAQ before submitting an issue:
- [x] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [x] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [x] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [x] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [x] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

**Comment by Scitator** [comment]
Hi,

Is it possible to use Sampler with train Dataset (`Dataloder(dataset=dataset, sampler=sampler)`) to make it the pre-defined number of batches you want?
