### ISSUE TITLE
comprehensive classification example

### ISSUE THREAD

**Issue by ashkanaev** [catalyst-team/catalyst#1421]
Hi, there

I used to train classification models using catalyst-classification project and found it convenient. But now it seems outdated (archived at least). Is there any classification example which perform pipeline like used before [here]( https://github.com/catalyst-team/classification/blob/master/bin/catalyst-classification-pipeline.sh). From the minimal examples it's not obvious how to configure train without coding directly.

Thank you!
Looking forward for your reply!

**Comment by Scitator** [comment]
hi, 
for full-feature config example, you could check out our [detection pipeline](https://github.com/catalyst-team/catalyst/tree/master/examples/detection). Additionaly, there [Config API - minimal example](https://github.com/catalyst-team/catalyst#minimal-examples) under minimal examples
