### ISSUE TITLE
KWArg fp16 does not exist

### ISSUE THREAD

**Issue by ppenlite** [catalyst-team/catalyst#1440]
# 🐛 BugReport
In my work I stumbled upon this line which often will create an engine with the `fp16` keyword argument. However, looking through the available engine classes, which eventually inherit from `Engine`, which in turn inherits from `Accelerator`, I noticed that this particular kwarg is not supported anymore and was replaced by `mixed_precision`. 
https://github.com/catalyst-team/catalyst/blob/e99f90655d0efcf22559a46e928f0f98c9807ebf/catalyst/runners/runner.py#L348

**Comment by YodaEmbedding** [comment]
Temporary workaround:

```bash
pip install accelerate==0.15.0
```

**Comment by ppenlite** [comment]
Wow, thanks for the super fast reply!
In fact my code doesn't run into this issue, yet, so I am pretty relaxed about it, but I had to mention it since it seems like this line, and the respective ones in `get_available_engine()` have been forgotten during the updates.

**Comment by Philmod** [comment]
Is there any plan to fix this issue? We need to use a later version of `accelerate`.

**Comment by djherbis** [comment]
@Scitator Sorry for the ping, any chance this might get looked at?
Kaggle is stuck on an old version of accelerate currently to keep catalyst, but thats hurting some other package installs.
We may have to drop catalyst support if we can't upgrade accelerate.
