### ISSUE TITLE
type object 'UtilsFactory' has no attribute 'create_tflogger'

### ISSUE THREAD

**Issue by amorgun** [catalyst-team/catalyst#18]
It looks like UtilsFactory is missing a method.
The error is in this line: https://github.com/Scitator/catalyst/blob/master/utils/factory.py#L50

**Comment by Scitator** [comment]
Hi,

Good catch, looks like something go wrong during https://github.com/Scitator/catalyst/pull/17.
Nevertheless, this one (https://github.com/Scitator/catalyst/commit/eaf8386320ae13e4b7be9b3361f1c50657868220) should fix the issue.

**Comment by amorgun** [comment]
I highly recommend importing `os` and `SummaryWriter` if you want to use them in this method.

**Comment by Scitator** [comment]
@amorgun That's right. fixed.
