### ISSUE TITLE
[devops] Move dependencies to PipEnv

### ISSUE THREAD

**Issue by andrey-avdeev** [catalyst-team/catalyst#192]
Now:
-  pip freeze -> requirements.txt - doesn't contains interpreter's version, hash sums e.t.c.
ToDo:
- install pipenv
- pipenv init && create Pipfile and Pipfile.lock
- test

P.S. pipenv repo - https://github.com/pypa/pipenv

**Comment by andrey-avdeev** [comment]
Done. Gonna create pull request today

**Comment by Scitator** [comment]
Closed due to poetry usage for deps logging.
