### ISSUE TITLE
[solved] Mixup feedback

### ISSUE THREAD

**Issue by ngxbac** [catalyst-team/catalyst#200]
It seems that [`mixup`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/mixup.py#L6) has not been updated for a long time.

I try this callback in version `19.05` and have some feedbacks and comments.

1. The mixup callback raises a [`None error`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/mixup.py#L19) 
The reason is, `state.input` has been not updated. 
The [`on_batch_start`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiments/core.py#L187) is called before a batch is assigned to [`state.input`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiments/core.py#L168) 
I took a look around your code, IMO, the `mixup` should be called before `batch prediction`. My current solution (locally) can work but maybe it is not suitable for your design. So, I leave this for your team.

2. Mixup is only applied to training 
The current code applies mixup for all steps (training, validation, inference) - if it works. 

3. Which is mixup correct? 
I refer to some implementations of mixup:
- mixup implemented by [`facebookresearch`](https://github.com/facebookresearch/mixup-cifar10/blob/master/train.py#L119) 
- mixup implemented by [`fastai`](https://github.com/fastai/fastai/blob/master/fastai/callbacks/mixup.py#L6) 
- Your mixup 
They are slightly different  :smile: 

4. Mixup loss 
I think mixup loss is necessary.

**Comment by Scitator** [comment]
Hi, 

You are right, the mixup was developed before the 19.02 version and so remains legacy piece of the catalyst. So, if you would like to contribute this functionality, I think, there are several steps in implementing... MixupLossCallback (?):
- during `batch_start` (before batch prediction) we need to permute the features and labels based on `self.lamda` & `self.alpha`
- during `batch_end` (after batch prediction) we need to recompute loss based on `self.lamda` & `self.alpha` (there is already an `_compute_loss` method implemented)

The implementation of [facebookresearch](https://github.com/facebookresearch/mixup-cifar10/blob/master/train.py#L119) is quite good and we have the same one, except that our permutations are not `torch.randperm` (so we can correct it, finally)

**Comment by ngxbac** [comment]
Hi, 
I understand the sequence 

> during batch_start (before batch prediction) we need to permute the features and labels based on self.lamda & self.alpha 

If you do `mixup` at the `batch_start`, you will get the error at the first batch as I mentioned above: `None error`. 

Please refer this: https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiments/core.py#L206

```
            self._run_event("batch_start")

            self.state.timer.start("_timers/model_time")
            self._run_batch(batch)
            self.state.timer.stop("_timers/model_time")

            self.state.timer.stop("_timers/batch_time")
            self._run_event("batch_end")
```

- At the first batch, after call: `self._run_event("batch_start")`, you will go to [this](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/mixup.py#L19) . 
`state.input[key]` will cause the `None error` because there is no `input` inside the `state`. 

- `input` is assigned in to `state` at the first time at [this line](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiments/core.py#L187). But this function is called `after batch_start` . That is the reason causes the bug. 

- This problem is related to the procedures of your system. I am scared to touch it. 
How do you think? 

Please give me the idea so that I can make a PR.

**Comment by Scitator** [comment]
HI,

First of all, don't be scared, the catalyst is quite flexible to handle different issues and evolve for features needs. 

The `None` bug should be fixed after https://github.com/catalyst-team/catalyst/pull/230. I hope, this would be enough to implement MixupCallback (btw, it was removed during https://github.com/catalyst-team/catalyst/pull/223, so it's an open question now). Nevertheless, I think [facebookresearch implementation](https://github.com/facebookresearch/mixup-cifar10/blob/master/train.py#L119) should work easily.

**Comment by lightforever** [comment]
@ngxbac, Hi.
There is an implementation of a mixup [here](https://github.com/lightforever/mlcomp/blob/master/mlcomp/contrib/catalyst/callbacks/mixup.py)

It works with the current master. Thanks to Scitator for the pull request #230
