### ISSUE TITLE
log_on_batch_end doesn't work in TensorboardLogger

### ISSUE THREAD

**Issue by ai-niki** [catalyst-team/catalyst#226]
When I add `log_on_batch_end=False` to `TensorboardLogger` it doesn't produce proper logs for tensorboard.

Tensorboard gives this error in logs (same for valid_log): `W0613 15:40:33.097291 123145404850176 core_plugin.py:172] Unable to get first event timestamp for run cifar_simple/train_log`

Steps to reproduce:
1. Add `log_on_batch_end=False` to `TensorboardLogger` in https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/state.py#L77
2. Install package (I used `pipenv install -e .`).
3. Run cifar_simple example.

MacOS 10.14.5
Python 3.6

**Comment by Scitator** [comment]
Looks like we have already fixes that issue :)
