### ISSUE TITLE
'async' is a reserved word in Python 3.7

### ISSUE THREAD

**Issue by cclauss** [catalyst-team/catalyst#3]
'__async__' is a reserved word in Python 3.7.  Cuda has shifted to '__non_blocking__' instead.  https://github.com/pytorch/pytorch/pull/4999

[flake8](http://flake8.pycqa.org) testing of https://github.com/Scitator/prometheus on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./losses/unet.py:8:23: E999 SyntaxError: invalid syntax
    return x.cuda(async=True) if torch.cuda.is_available() else x
                      ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by Scitator** [comment]
Good catch! 
Unet code will be refactored soon for segmentation tutorial purposes.
Nevertheless, I have updated docs and codestyle for correctness.
