### ISSUE TITLE
[proposal] Visdom support

### ISSUE THREAD

**Issue by i-zaitsev** [catalyst-team/catalyst#344]
You probably know about a great dashboard library called [`visdom`](https://github.com/facebookresearch/visdom) that helps to easily report training logs and stats when working with PyTorch. Especially for basic cases when one just needs to draw a loss curve. For example, if you want to send a tensor parameter into dashboard, you can do something like this:
```python
vis = Visdom(**visdom_params)
vis.line(X=[step], Y=[value], win='loss', name='train_loss', update='append')
```
And the value will show up in the dashboard's window. 

It would be great to have at least some basic integration with the `catalyst` library, like this simple callback:
```python
import os
from catalyst.dl.core import Callback
from visdom import Visdom

class VisdomCallback(Callback):
    
    def __init__(self, 
                 username='username', password='password', 
                 host='0.0.0.0', port=9090, use_env_creds=False):
        """
        Args:
            username (str): Visdom server username.
            password (str): Visdom server password.
            host (str): Visdom server address.
            port (int): Visdom server port.
            use_env_creds (bool): If True, then ignore credentials
                passed as __init__ parameters and use Visdom 
                environment variables instead.
        """
        
        super().__init__()

        if use_env_creds:
            username = os.environ['VISDOM_USERNAME']
            password = os.environ['VISDOM_PASSWORD']
            
        self.vis = Visdom(
            username=username, password=password,
            server=host, port=port)        

        
class BatchMetricsPlotCallback(VisdomCallback):

    def on_batch_end(self, state):
        for k, v in state.metrics.batch_values.items():
            self.vis.line(X=[state.step], Y=[v], win=k, name=k, update='append')
```

Do you think that could be a good idea to include something like this into `catalyst`? Would be glad to hear your thoughts.

**Comment by Scitator** [comment]
Hi,
Proposal looks great! 
Would you like to contribute something like VisdomLogger (you can take the logic from [Tensorboard one](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/logging.py#L113))?

And it looks like we need to add this logger to `state.loggers`, somewhere [here](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/core/state.py#L83).
Maybe we should help you with loggers logic refactoring, it is a little bit outdated now.

**Comment by i-zaitsev** [comment]
@Scitator ok great! Sure, let's try to figure it out. I'll create a PR with some proposal and then we can adjust it to the codebase and vice versa.

**Comment by Scitator** [comment]
@devforfu Hi, is this issue still alive?)
