### ISSUE TITLE
Change API for valid_loader='train' (when validation is empty)

### ISSUE THREAD

**Issue by DBusAI** [catalyst-team/catalyst#360]
This is quite frequent feature. The simplest way to do it - just add 
```
if "valid" not in loaders.keys():
            valid_loader = "train" 
```
in catalyst/dl/runner/supervised.py
Am i right?

**Comment by Scitator** [comment]
I think, it is better to check, that there is only one loader and use its key.
Nevertheless, you also need to warn user, cause you can easily forget to pass several loaders :)

**Comment by DBusAI** [comment]
It has to be smth like this ? 
```
import logging
logger = logging.getLogger(__name__)
...
if len(loaders)==1:
            valid_loader = list(a.keys())[0]
            logger.warning(
                "Attention,there is only one data loader - " + str(valid_loader)
            )
```

**Comment by Scitator** [comment]
Looks good 👍

**Comment by Scitator** [comment]
fixed https://github.com/catalyst-team/catalyst/pull/362
