### ISSUE TITLE
AccuracyCallback with OneHotEncoded throws up errors.

### ISSUE THREAD

**Issue by Thanatoz-1** [catalyst-team/catalyst#364]
When working with simple classification problem, the SupervisedRunner throws up the following error:
```
RuntimeError: The expanded size of the tensor (32) must match the existing size (3264) at non-singleton dimension 1.  Target sizes: [5, 32].  Tensor sizes: [1, 3264]
```

Just to simplify, it is asking me to remove the one-hot-encoding from the labels and predictions. Could you suggest how can I get through it?

32 - is the batch size
102 is the number of classes

**Comment by TezRomacH** [comment]
If I understand you correctly, you need to mix the targeting in non-one_hot format into the data set, like here:
https://render.githubusercontent.com/view/ipynb?commit=9bce7ef869d52acd83cae40698fff7f31aa09fd4&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f636174616c7973742d7465616d2f636174616c7973742f396263653765663836396435326163643833636165343036393866666637663331616130396664342f6578616d706c65732f6e6f7465626f6f6b732f636c617373696669636174696f6e2d7475746f7269616c2e6970796e62&nwo=catalyst-team%2Fcatalyst&path=examples%2Fnotebooks%2Fclassification-tutorial.ipynb&repository_id=145385156&repository_type=Repository#Augmentations


and in the `AccuracyCallback` set `input_key=<your non-one_hot-target>`
