### ISSUE TITLE
Feature request tiled inference

### ISSUE THREAD

**Issue by ternaus** [catalyst-team/catalyst#384]
It would be a killer feature for medical and satellite imagery tasks to run inference on large images.

Example: https://github.com/BloodAxe/pytorch-toolbelt#inference-on-huge-images

**Comment by Scitator** [comment]
As `pytorch-toolbelt` is Catalyst-friendly lib and already have an example, would you like to make a PR?

**Comment by Scitator** [comment]
Hi,
Do you have any update on your issue/proposal/possible-pr?

**Comment by Scitator** [comment]
closed due to inactivity

**Comment by pdanilov** [comment]
Please re-open it. I'm on my way to implement this thing right now.

**Comment by Scitator** [comment]
@pdanilov deal, thank you for your future contribution :)
