### ISSUE TITLE
Add more details to CONTRIBUTING.md

### ISSUE THREAD

**Issue by sergeyshilin** [catalyst-team/catalyst#400]
There are two options I see:

1. `pip install -r requirements/requirements-dev.txt`, `pytest` version has to be upgraded (current one fails)
2. List libraries to install in the `CONTRIBUTING.md` file: `flake8`, `flake8-quotes`, `yapf`, `pytest`, `sphinx`

**Comment by Arquestro** [comment]
I guess these problems have been solved with PR for this issue https://github.com/catalyst-team/catalyst/issues/436
