### ISSUE TITLE
Cover catalyst-data process-images with tests

### ISSUE THREAD

**Issue by sergeyshilin** [catalyst-team/catalyst#401]
1. Load jpg/jpeg dataset tests
2. Load png dataset tests (some other formats?)
3. Match the number of images processed
4. Match the file size after processing
5. Test parameters --grayscale, --clear-exif, --expand-dims

**Comment by Scitator** [comment]
Hi,
@sergeyshilin Are you proposing a PR with such test coverage? Or you are looking for such tests?

**Comment by sergeyshilin** [comment]
As far as I recall, I was not proposing a PR, but found it necessary to cover those scenarios with tests. I guess it can be closed if Catalyst is not planning to implement such tests in the near future.
