### ISSUE TITLE
[proposal] Add never_show_list to VerboseLogger

### ISSUE THREAD

**Issue by ostamand** [catalyst-team/catalyst#414]
When logging a lot of metrics, we sometimes don't want to show all of them in the console. 
For example, when looking at the means & stds of 10+ activations. 

Proposal is to add a `never_show_list` to `VerboseLogger`.

```python
class VerboseLogger(Callback):
    def __init__(
        self,
        always_show: List[str] = ["_timers/_fps"],
        never_show: List[str] = []
    ):
        """
        Log params into console
        Args:
            always_show (List[str]): list of metrics to always show
        """
        super().__init__(CallbackOrder.Logger)
        self.tqdm: tqdm = None
        self.step = 0
        self.always_show = always_show
        self.never_show = never_show
        for k in never_show:
            assert k not in always_show      
```

That way, it is possible to exclude easily metrics for the console logging while keeping them in the logs files for further analysis using `TensorBoard` or `plot_metrics`.

```python
act_callback = MonitorActivations(model) 
callbacks=[
    VerboseLogger(never_show=[*act_callback.metrics_mean, *act_callback.metrics_std]),
    act_callback
]
```

Let me know what you think of this small change.

Thanks

**Comment by TezRomacH** [comment]
The PR is still under development, but I work on this feature :)

https://github.com/catalyst-team/catalyst/pull/443/commits/1f945a79015d315ecf09851357e734fa9b0ed7a9

**Comment by ostamand** [comment]
Sweet! I will close this issue.

**Comment by ostamand** [comment]
Bah let's keep opened while the PR is being developed. That way people will know the  feature is being developed.

**Comment by TezRomacH** [comment]
Added :)

**Comment by ostamand** [comment]
Sweet. Thank you!
