### ISSUE TITLE
Text sentiment classification tutorial

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#426]
**Is your feature request related to a problem? Please describe.**
We need a simple NLP-related tutorial on Catalyst with a sentiment classification task.

**Describe the solution you'd like**
A well-documented notebook with name `nlp-sentiment-tutorial.ipynb` in `catalyst/examples/notebooks/` folder.

It has to use PyTorch and Catalyst as a train-loop.

**Describe alternatives you've considered**
We have examples for 
- [Classification tutorial](examples/notebooks/classification-tutorial.ipynb) [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/classification-tutorial.ipynb) for CV
- [Segmentation tutorial](./examples/notebooks/segmentation-tutorial.ipynb) [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb) for CV

**Comment by lightforever** [comment]
Related issue: https://github.com/catalyst-team/bert/issues/3

There is a plan to union https://github.com/catalyst-team/bert/ and Catalyst and create a text classification example.

**Comment by Scitator** [comment]
done
