### ISSUE TITLE
Add trace method to SupervisedRunner

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#430]
**Is your feature request related to a problem? Please describe.**
We have tracing support for Config API (https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/scripts/trace.py). Usage example: https://github.com/catalyst-team/catalyst-info#catalyst-info-2-tracing-with-torchjit

But our Notebook API doesn't support it yet.

**Describe the solution you'd like**
Add to SupervisedRunner method `trace`, which uses `torch.jit`
https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/runner/supervised.py#L17

**Comment by Scitator** [comment]
done
