### ISSUE TITLE
Fix in BaseCheckpointCallback `_metrics` not only for the last stage but for all

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#431]
**Describe the bug**
Now the `_metrics.json` file created by [BaseCheckpointCallback](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/checkpoint.py#L13) stores only the latest stage metrics (because the file is [simply overwritten there](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/checkpoint.py#L30))

We need to make a normal metric manager for this checkpoint.

**To Reproduce**
1. Add a config file with several training stages.
2. Add a [CheckpointCallback](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/checkpoint.py#L77) with `save_n_best` > 1 to store several best checkpoints (for example 3)
3. In `logdir/checkpoints/_metrics.json` we have logs only for the last stage

**Expected behavior**
Metrics are logged from all the stages.

**Comment by Arquestro** [comment]
I'll work on this one.

My first thoughts on this is to add default argument for custom metrics filename in BaseCheckpointCallback:
```
def save_metric(self, logdir: str, metrics: Dict, custom_metric_filename: str=None) -> None:
    if custom_metric_filename is None:        
        safitty.save(metrics, f"{logdir}/checkpoints/{self.metric_filename}")
    else:
        safitty.save(metrics, f"{logdir}/checkpoints/{self.custom_metric_filename}")
```

And in CheckpointCallback:
```
self.save_metric(logdir, metrics, custom_metric_filename=f"_metrics_{suffix}.json")
```

Something like that. I'll check the implementation myself, because i feel that there is something else has to be done with callbacks to get it working right. :)

**Comment by Arquestro** [comment]
Or we can just change `metric_filename `in `CheckpointCallback `before saving, and don't touch `save_metric` in `BaseCheckpointCallback`.

**Comment by Arquestro** [comment]
I guess there is more to that: we need to delete the metric that got popped out from N-best ones.

**Comment by Arquestro** [comment]
I've ran an example on master unchanged code catalyst/examples/_tests_mnist_stages/config1.yml, but with 9 stages.
Got a _metrics.json file with 3 checkpoints + last and best.

I think that for collecting all metrics we need to add separate metrics list with all the metrics and make one save for this one at stage end in separate file.

Or we can save all metrics + n_best + best + last in one metrics file, if that suits our needs more.

Got a thought that a PR will be more than a thousand words. :)
