### ISSUE TITLE
Add runner_params for Runner in Config API

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#434]
**Is your feature request related to a problem? Please describe.**
When initializing SupervisedRunner, you can set many useful parameters: `input_key`, `output_key` and `input_target_key`.

However, with ConfigAPI, the Runner [is imported and initialized](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/scripts/run.py#L76) without parameters:
```python
Experiment, Runner = import_experiment_and_runner(Path(args.expdir)
runner = Runner()
```

Because of this, unfortunately, we have to create new classes, like
```python
class ModelRunner(Runner):
    def __init__(self):
        super().__init__(input_key="image", output_key=None)

# or even worse
class ModelRunner(Runner):
    def predict_batch(self, batch: Mapping[str, Any]):
        output = self.model(batch["image"])
        return output
```

It is bad to create a class that differs only in the parameters for initialization, so there is an idea.
Add the ability to write `RUNNER_PARAMS` (naming is not critical) in the` __init__.py` file and catch it when importing.

**Describe the solution you'd like**

```python
# in `__init__.py`

from catalyst.dl import SupervisedRunner as Runner
RUNNER_PARAMS = dict(input_key="image", output_key=None)
```

And when `catalyst-dl run` is executing
```python
Experiment, Runner, runner_params = import_experiment_and_runner(Path(args.expdir)

runner_params = runner_params or {}
runner = Runner(**runner_params)
```

**Comment by Arquestro** [comment]
I'll work on this one, next PR.

**Comment by Scitator** [comment]
done
