### ISSUE TITLE
Add native Tensorboard from PyTorch

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#435]
**Is your feature request related to a problem? Please describe.**
All Tensorboard logs are currently saved with TensorboardX. Since version 1.2, PyTorch has received native support via `torch.utils.tensorboard`.

**Describe the solution you'd like**
Guided by these two tutorials:
- [TORCH.UTILS.TENSORBOARD](https://pytorch.org/docs/stable/tensorboard.html)
- [VISUALIZING MODELS, DATA, AND TRAINING WITH TENSORBOARD](https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html)

it is time to move Catalyst to tensorboard from PyTorch.

After that, in `requirements/requirements.txt`, increase the minimum version of PyTorch to 1.2.

**Comment by Arquestro** [comment]
I can look into this one, i'll try to make sane changes and send PR tomorrow on that.
But, PyTorch version migration can bring it's own surprises to whole repo imo.

**Comment by Arquestro** [comment]
Guess we can close it now :)

**Comment by Arquestro** [comment]
Pull request head message is confusing btw.
Next time i'll try to edit it before merge. Or isn't worth it?
