### ISSUE TITLE
Flake8 error while executing "make codestyle" command

### ISSUE THREAD

**Issue by Arquestro** [catalyst-team/catalyst#436]
**Description:**
Command "make codestyle" exits with flake8 error: "no such option: --inline-quotes".

**To reproduce:**
1. Install flake8, version 3.7.8.
3. Run "make codestyle" in root of catalyst repository on HEAD if master remote branch.

**Expected:**
Codestyle checked successfully with no errors from flake8.

**Screenshot:**
![image](https://user-images.githubusercontent.com/7341001/66612377-4c726f80-ebca-11e9-8301-bb68718807fe.png)

**Comment by Scitator** [comment]
Hi, @Arquestro 

Thanks for reporting! Could you please `pip install -r ./requirements/requirements-dev.txt`? We have additional flake extensions for code-style check :)
Somehow, we have just forgot to add this like to contribution guide. Is it okay for you to check `pip install` and make a PR with contribution guide update? As a person, who have just passed this relevant experience you could propose better vision of docs update.

**Comment by Arquestro** [comment]
Thanks for update, ill check it and do my best :)

**Comment by Scitator** [comment]
Done :)
