### ISSUE TITLE
Distributed training tutorial

### ISSUE THREAD

**Issue by TezRomacH** [catalyst-team/catalyst#442]
**Is your feature request related to a problem? Please describe.**
We need a tutorial about distributed training in Config API using Catalyst

**Describe the solution you'd like**
A Config API project in `examples` folder (you can create an empty project with `catalyst-dl init` and finish it)

It has to use PyTorch and Catalyst as a train-loop.

Needed features:
- A couple of ec2 instances initialized.
- The model is trained there in distributed mode.
- Weights are uploaded to Weights&Biases.
- Instances are closed.

And the tutorial should explain how to run such training.

```
export MASTER_ADDR="127.0.0.1"
export MASTER_PORT=29500
export WORLD_SIZE=2 # number of GPUs

RANK=0 LOCAL_RANK=0 catalyst-dl run --config=configs/exp_splits.yml --distributed_params/rank=0:int & # on GPU-0
sleep 5 # sleep for a while, because there's a python source copying and arguing
RANK=1 LOCAL_RANK=1 catalyst-dl run --config=configs/exp_splits.yml --distributed_params/rank=1:int & # on GPU-1
```

**Describe alternatives you've considered**
We have a good [Config API tutorial](https://github.com/catalyst-team/classification) for image classification.

**Comment by ternaus** [comment]
> We need a tutorial about distributed training in Config API using Catalyst

I am actually more interested in jupyter API. Can we extend the tutorial?

**Comment by TezRomacH** [comment]
@ternaus 
This is a bit more complicated for the Notebook API. I suggest we make the first tutorial for Config and then look at Notebook.

**Comment by Scitator** [comment]
done
