### ISSUE TITLE
MPI support ? 

### ISSUE THREAD

**Issue by znake77** [catalyst-team/catalyst#453]
Hi All, 

Thanks for sharing this project !  Really enjoying playing with it. 
I have a question regarding multiprocessing and cohabitation between Catalyst framework and MPI.
I have some code that uses CMAES and MPI to dispatch the work to different worker. I use that to learn low level controllers to be used in combination with RL controller. 

To launch my CMAES optimization I do something like this : 

`mpirun -hostfile hostfile /home/jkr/run_mpi -n 28 -g 1000 -t CMAES -c checkpoints/checkpoint_155.pkl`.

Then the mpirun wrapper dispatches the python controller. Know I noticed that Catalyst uses multiprocess to do multiprocessing. 

I noticed that multiprocessing is used in those files : 

```
catalyst/utils/parallel.py:9:from multiprocessing.pool import Pool
catalyst/rl/core/trajectory_sampler.py:4:import multiprocessing as mp
catalyst/rl/core/sampler.py:13:import multiprocessing as mp  # noqa E402
catalyst/rl/utils/buffer.py:4:import multiprocessing as mp
catalyst/rl/scripts/run_samplers.py:11:import multiprocessing as mp  # noqa E402

```

I guess that it is mainly the `run_samplers.py` that would need to be adapted since its the process actually running the environment. What effort would it require to make Catalyst compatible with mpirun ? I am happy to work on a pull request if somebody is interested, I know that catalyst uses a db, so I guess that is how the samplers sends information to the trainer. Is this correct ? Any high level information would help me !

Thanks

**Comment by lightforever** [comment]
Hi. Pardon, I don't understand your issue. 

Could you, please:

- describe the problem. Does the Catalyst hangs or crashes?

- provide us with a fully-reproducible example

**Comment by Scitator** [comment]
closed due to inactivity
