### ISSUE TITLE
TelegramCallback for SupervisedRunner

### ISSUE THREAD

**Issue by andrey-avdeev** [catalyst-team/catalyst#466]
It will be helpful to add telegram notification into supervised runner.

User will be able to receive score, epoch number e.t.c. right into his mobile & this integration requires only requests module dependency.

Solution:
Additional callback, where you should point channel_id, telegram_bot_token and message template.

Alternative - add slack or universal webhook callback

**Comment by Scitator** [comment]
merged & done, thanks!
