### ISSUE TITLE
Remove log's strings with last batch info after epoch ends

### ISSUE THREAD

**Issue by ruslangrimov** [catalyst-team/catalyst#467]
**Is your feature request related to a problem? Please describe.**
After a train epoch ends there are four rows left in the log. 
```
0/25 * Epoch (train): 100% 156/156 [..., loss=0.815]
0/25 * Epoch (valid): 100% 18/18 [..., loss=0.942]
[2019-10-22 00:53:53,000] 
0/25 * Epoch 0 (train): _base/lr=0.0010 | ... | loss=0.9417
0/25 * Epoch 0 (valid): _base/lr=0.0010 | ... | loss=1.1581
```
Two last rows contain summary information about the entire epoch. Two first contain information about last train and valid batches. The latest is not much important and yet confusing.

**Describe the solution you'd like**
It would be nice if there were only two rows left after an epoch ends with only summary information.

**Comment by Scitator** [comment]
To remove additional logging during training you can remove `verbose` flag :)
