### ISSUE TITLE
"Lifted Struct Loss" feature request

### ISSUE THREAD

**Issue by smivv** [catalyst-team/catalyst#468]
"Lifted Struct Loss" feature request.

Paper: https://arxiv.org/abs/1511.06452
Implementations:
1. https://github.com/bnu-wangxun/Deep_Metric/blob/master/losses/LiftedStructure.py
2. https://gist.github.com/bkj/565c5e145786cfd362cffdbd8c089cf4

**Comment by Scitator** [comment]
Dear @smivv 
Would you like to make a PR with such functionality? Just like our TripletLoss epic :likeacatalyst:

**Comment by Scitator** [comment]
contrib issue
