### ISSUE TITLE
Attribute Error in the resume feature.

### ISSUE THREAD

**Issue by nischal-sanil** [catalyst-team/catalyst#469]
Hello,

If I set the resume argument and give a list of callbacks, then I get an attribute error `AttributeError: 'list' object has no attribute 'values'` from [this line](https://github.com/catalyst-team/catalyst/blob/fddb516cc380380f1777dad5aef27fd298375ca2/catalyst/dl/runner/supervised.py#L171).

But If I give `CheckpointCallback(resume=checkpoint)` with the list of callbacks, it works.

Is that how it is suppose to work?

**Comment by the-lay** [comment]
Stumbled upon the same issue, specifying resume through SupervisedRunner crashes with `'list' object has no attribute 'values'`.

**Comment by Scitator** [comment]
please check the last version, we should fixed this issue.
