### ISSUE TITLE
less verbose mode - progressbar exhausts stdout in kaggle kernels

### ISSUE THREAD

**Issue by virilo** [catalyst-team/catalyst#470]
I'm using catalyst in the context of Kaggle competitions, using Kaggle kernels/notebooks

After some epochs, the log gets truncated:

... stdout truncated after 1,048,576 bytes ...

The problem is that the progressbar is very verbose, and writes a new line per step.

**Describe the solution you'd like**

It could be great to have a less verbose mode, just one line per epoch

Thanks a lot for Catalyst!

**Comment by TezRomacH** [comment]
For a basic solution, you can disable `verbose` flag and view logs through tensorboard.

**Comment by Scitator** [comment]
Thanks to Logger restructuration, you can handle logging metrics.
Please check [LoggerCallback](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/logging.py#L17)
