### ISSUE TITLE
Symmetric Cross Entropy

### ISSUE THREAD

**Issue by 421psh** [catalyst-team/catalyst#479]
"Symmetric Cross Entropy" feature request.

Paper: https://arxiv.org/abs/1908.06112
Implementations:

    https://github.com/YisenWang/symmetric_cross_entropy_for_noisy_labels
    https://github.com/HanxunHuangLemonBear/SCELoss-Reproduce

Thank you a lot for the Catalyst

**Comment by Scitator** [comment]
Hi, thanks for the papers.
Would you like to make a PR for our contrib.losses?

**Comment by Scitator** [comment]
done, thanks!
