### ISSUE TITLE
runner.train(resume=resume_path) failed

### ISSUE THREAD

**Issue by wmmxk** [catalyst-team/catalyst#489]
**Describe the bug**
I was trying to resume my training of a model. The resume_path is a string "./saved_model/best.pth". 
I run into this error:
    168             checkpoint_callback_flag = any([
    169                 isinstance(x, CheckpointCallback)
--> 170                 for x in callbacks.values()
    171             ])
    172             if not checkpoint_callback_flag:

AttributeError: 'list' object has no attribute 'values'

The error seems not related to the checkpoint but to the callbacks. For the callbacks argument, here is what I passed in ```callbacks=[DiceCallback(), EarlyStoppingCallback(patience=5, min_delta=-0.1)],```
I think I was using the runner.train() fucntion in a incorrect way because catalyst is very good other than this.
Has anyone have similar experience?

**Comment by SindhuVenna** [comment]
I had the same issue.
Modify line 167 to **callbacks = process_callback(callbacks)** 

after importing from **catalyst.dl.utils import callbacks**

After making this change , it works as expected. The code didnot consider the case when callbacks is a list and not a dictionary. Adding that line corrects it.

**Comment by Scitator** [comment]
Looks like solved :)
