### ISSUE TITLE
[Question] is it possible to save both best loss checkpoint and best metric checkpoint??

### ISSUE THREAD

**Issue by bamps53** [catalyst-team/catalyst#490]

**Comment by TezRomacH** [comment]
Hi! At the moment, there is no such possibility, for CheckpointCallback we take `state.main_metric`, but the idea to pass `reduce_metric` as in SchedulerCallback is excellent!

Would you like to contribute this feature? :)

**Comment by bamps53** [comment]
Thanks, I'll try!!
