### ISSUE TITLE
AMP wants the model to be first sent to CUDA device

### ISSUE THREAD

**Issue by Yorko** [catalyst-team/catalyst#494]
**Describe the bug**
When training with `fp16`, AMP says that we need to provide a model with parameters located on CUDA. 

**To Reproduce**
The problem is reproduced in [this Kernel](https://www.kaggle.com/kashnitsky/distillbert-catalyst-amazon-product-reviews?scriptVersionId=22987225) (Version 3). 

**Expected behavior**
Expect the model to train normally

**Screenshots**
Calling `runner.train` 

<img src="https://habrastorage.org/webt/fd/rp/0i/fdrp0i4u6uzxhyd5wjafuc1k3w0.png" />

Getting error:
```
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.
```
<img src="https://habrastorage.org/webt/a1/im/vo/a1imvo0wsnv2vuddgdteglhu0ua.png" />

**Additional context**
The problem is solved if I pass `model=model.cuda()` to `runner.train`. But I don't think it's designed to be done like that. 

Catalyst version is 19.11.

**Comment by Yorko** [comment]
The issue happened when using Kaggle. Strange. This is not reproduced on my machine. Trains fine.

**Comment by bamps53** [comment]
I had same issue when I use Catalyst 19.11. on google colab. When I change the version to 19.10, the error didn't show up.

**Comment by TezRomacH** [comment]
🤔

**Comment by TezRomacH** [comment]
@Yorko try now with `19.11.1` please

**Comment by Yorko** [comment]
Looks like it's fine now, same [Kernel](https://www.kaggle.com/kashnitsky/distillbert-catalyst-amazon-product-reviews), 11th version. Closing.
