### ISSUE TITLE
Shape mismatch in F1ScoreCallback

### ISSUE THREAD

**Issue by Yorko** [catalyst-team/catalyst#495]
**Describe the bug**
Get this when I add `F1ScoreCallback` to `runner.train`:

```
The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1
```
Here 4 is batch size, and 3 is the number of classes.

**To Reproduce**
A bit tedious. So I'm attaching [the notebook](https://drive.google.com/file/d/1bcuav_Z_iwqZvIkpf7eC9iOhmuqd-Km6/view?usp=sharing) reproducing the error. 

**Screenshots**
<img src="https://habrastorage.org/webt/jc/x5/ew/jcx5ew0a8m2nicsfopvo-8ucca8.png" />

**Additional context**
Catalyst version is 19.11.

**Comment by Scitator** [comment]
Fixed :)
