### ISSUE TITLE
Infer stages

### ISSUE THREAD

**Issue by gazay** [catalyst-team/catalyst#512]
My idea is to separate train stages from infer stages. In train stages could be lots of common params, and it is useful to have the possibility to write, for example common `state_params` section where you can set `num_epochs` to 3 for all train stages. But in most cases, it will be meaningless for infer stage - you don't want to run your inference process three times. The same thing about criterion and other possibly "common" pipeline blocks of train stages - it just will not work through the inference stage as you don't have `targets`.

Also, storing train and infer stages inside one parent `stages_params` section raises problems on differentiation of logic according to stage name (some of the functions will be skipped if stage name starts with `infer`) - that could work in general. Still, it's not incorporated in all abstractions one can define in common stages section (or when implemented custom components). 

I can think of a couple of possible solutions:
1. To use differently named parent sections - `train_stages_params` and `infer_stages_params`
2. To allow several `stages_params` and differentiate them by required `mode` attribute, which could take one of `["train", "valid", "infer" ...]` modes. I see it as a more flexible solution than 1, but it will bring a bit more overhead in config parsing logic with shadowy benefit (but it's maybe because I can't imagine a lot of cases when we would need more than two groups of stages).

**Comment by Scitator** [comment]
Not sure, if we really need it, it looks like additional complexity for both understanding and config parsing, isn't it?

**Comment by gazay** [comment]
Yeah, easier to make separate config
