### ISSUE TITLE
Metrics callbacks should support ignore label

### ISSUE THREAD

**Issue by sergregory** [catalyst-team/catalyst#516]
**Description**
Sometimes, not all samples in the dataset have annotations for all labels. In this situation, common solution is to use special "ignore" value for the not annotated label. However, one-hot encoding, that is required for many metrics callback (e.g. AUCCallback) does not support ignore labels (this is by design of one-hot encoding, for sure), so we cannot calculate metrics for such datasets.

**Proposal**
The idea is to provide two additional parameters for the metrics callbacks:
- labels_filter - any callable, that will take labels list and return indices of labels to preserve
- labels_encoder - any callable, that will take labels and convert them to one-hot like form.
By default, these two params should be None and `one_hot`, correspondingly.

**Describe alternatives you've considered**
As an alternative, I can imagine the user preparing encoded labels together with the list of indices of valida labels, to use in the callback, but it sounds like a pain.

**Comment by Scitator** [comment]
Dear @sergregory,
Is this issue still valuable? And do you have any proposals for feature implementation?

**Comment by Scitator** [comment]
closed due inactivity and because we have full support for any `metric_params` for current MetricCallback.
