### ISSUE TITLE
Supervised runner stuck at 0 percent

### ISSUE THREAD

**Issue by TimSYQQX** [catalyst-team/catalyst#518]
**Describe the bug**
When I run Supervisedrunner().train(). The progression bar is stucked and the system freeze when I try to terminate the process in anyways. 

**To Reproduce**
1. Use ubuntu 18.04LTS
2. create a python3.7 Conda environment
3. run https://www.kaggle.com/timsyqqx/segmentation-in-pytorch-using-convenient-tools in that environment.  

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TimSYQQX** [comment]
Also, its worth noting that I'm using ryzen 1700 processor. After tracing the process, it seems like its a threading problem.

**Comment by Scitator** [comment]
Please, try to use different `torch` version, there are several issues with gpus compatibility.
