### ISSUE TITLE
Configurable checkpoints

### ISSUE THREAD

**Issue by gazay** [catalyst-team/catalyst#520]
Right now checkpoint logic in Config API is following: if it's not a first stage, then we'll take `{logdir}/checkpoints/best.pth` as a checkpoint (https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L117-L121)

I think that would be great and more flexible if we'll add possibility to configure this behavior. What comes in mind:

1. We can add an option on `stages` level to allow to ignore this default behavior and teach each `stage` independently. This way we would be able to teach different folds from one config, different models etc.
2. We can add an option on specific `stage` level to set where to find checkpoint. It will allow us to start not from scratch but from some state even on the first `stage`.
3. Also we can add some param to `infer stage` to allow it to use different checkpoints (and maybe multiple checkpoints and some strategy - how to ansamble those predictions). This one seems as separate interesting feature

**Comment by Scitator** [comment]
I think, we have resolved this issue already :)
