### ISSUE TITLE
Bug in MulticlassIOUMetricCallback & MulticlassDiceMetricCallback

### ISSUE THREAD

**Issue by smivv** [catalyst-team/catalyst#530]
Ciao guys,

I am receiving ```AttributeError: 'numpy.ndarray' object has no attribute 'items'``` error in [this line](https://github.com/catalyst-team/catalyst/blob/b80857391ff1ac752e5a498fe761d2d377b63146/catalyst/dl/callbacks/metrics/iou.py#L126), probably because ```calculate_jaccard``` function  [returns](https://github.com/catalyst-team/catalyst/blob/b80857391ff1ac752e5a498fe761d2d377b63146/catalyst/dl/callbacks/metrics/iou.py#L58) numpy.ndarray.

One of possible solutions, maybe, is to refactor ```calculate_jaccard``` function in order to return dictionary of class_ids and iou values.

**Comment by smivv** [comment]
And seems like we have the same issue for ```MulticlassDiceMetricCallback```.

**Comment by Scitator** [comment]
Dear @smivv could you please check if the bug is still raised? We have updated these callbacks.

**Comment by ai-niki** [comment]
@Scitator there is no such bug now, you can close this issue
