### ISSUE TITLE
Pycharm debugger problems with logdir==''

### ISSUE THREAD

**Issue by Zillibub** [catalyst-team/catalyst#537]
**Describe the bug**
If I'll set logdir='' in runner.train method, folder code will be created. 
That folder will become source of an unexpected behavior on next code runs of this script in PyCharm debugger. 

During PyCharm debugger start following code will be evaluated: 
```
try:
    from code import InteractiveConsole
except ImportError:
    from _pydevd_bundle.pydevconsole_code_for_ironpython import InteractiveConsole
```
And will end up with error 
`ImportError: cannot import name 'InteractiveConsole'`
`SyntaxError: Missing parentheses in call to 'exec'`
Because there are folder /code is present in the same location as script, it can be interpreted not as pycharm code.py, but as independent module if there are \_\_init__.py in it (it is possible, because all folder with script will be copied to folder /code). 
I think this is a very unusual behavior, it took me some time to point the problem, so at least some warnings will be perfect.  

**To Reproduce**
1. Create script main.py with runner evaluation
2. Create \_\_init__.py file in the same folder
3. Set logdir=''
4. Run script main.py
5. Rerun script with PyCharm debugger

**Expected behavior**
There are several ways to avoid that possible problem
1. Change folder name from /code to something else
2. Do not copy \_\_init__.py file into /code folder
3. Show a warning that logdir='' might cause some problems

**Comment by Scitator** [comment]
Do you have any troubles with `logdir="./path/to/logdir"` variant?

**Comment by Scitator** [comment]
closed due to inactivity
