### ISSUE TITLE
Incorrect tensorflow versions comparison 

### ISSUE THREAD

**Issue by Inkln** [catalyst-team/catalyst#548]
**Describe the bug**
https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/seed.py incorrect compare of tf versions 
`if tf.__version__ >= "2.0.0":
            tf.random.set_seed(seed)
        elif tf.__version__ <= "1.13.2": # here ("1.4.1" <= "1.13.2") is False
            tf.set_random_seed(seed)
        else:
            tf.compat.v1.set_random_seed(seed) # And code fails here
`

**To Reproduce**
1. install tensorflow 1.4.1 or 1.3.1 or similar before catalyst

**Expected behavior**
  tf.set_random_seed(seed) is called

**Screenshots**

**Additional context**

**Comment by gazay** [comment]
@Avi2011class is this issue is solved by https://github.com/catalyst-team/catalyst/pull/547 and can be closed?

**Comment by Inkln** [comment]
Yes, it's solved
