### ISSUE TITLE
Incorrect Tensorboard import

### ISSUE THREAD

**Issue by Podidiving** [catalyst-team/catalyst#557]
**Describe the bug**
in https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/tensorboard.py
```python
from torch import __version__ as torch_version  # noqa: E402
from packaging import version  # noqa: E402
if version.parse(torch_version) < version.parse("1.2.0"):
    from tensorboardX import SummaryWriter as tensorboardX_SummaryWriter
    SummaryWriter = tensorboardX_SummaryWriter
else:
    from torch.utils.tensorboard import SummaryWriter as torch_SummaryWriter
    SummaryWriter = torch_SummaryWriter
if version.parse(torch_version) < version.parse("1.2.0"):
    from tensorboardX.proto.event_pb2 import Event
else:
    from tensorboard.compat.proto.event_pb2 import Event
```
There is incorrect `SummaryWriter` and `Event` imports while having tensorboard < 1.14.0

**To Reproduce**
1. torch==1.3.1
2. tensorboard==1.12.2
3. from catalyst.dl import utils

**Expected behavior**
`from tensorboardX import SummaryWriter` and `from tensorboardX.proto.event_pb2 import Event` are called

**Screenshots**
![image](https://user-images.githubusercontent.com/26285240/70820129-f64bc380-1de8-11ea-96ea-633437676835.png)

**Additional context**

**Comment by Arquestro** [comment]
Hello! Thank you for the report. I don't think that this issue can be considered as a bug, because there is latest version of tensorboard in requirements.txt.

**Comment by Podidiving** [comment]
Hi! Yes, I totally agree, but if you first install tensorboard of the old version and then catalyst, you will have the wrong version of tensorboard
Plus, i believe, that this can be easily fixed by additional version checking in if-statement

**Comment by Arquestro** [comment]
I guess it can be fixed with requirements rewrite. Just need to change the requirements to `tensorboard>=1.14.0`, instead of plain `tensorboard`.
No need for checking old versions, there will be more pain of legacy support. Even this import decision was not easy, and has been made this way because most users are still on PyTorch version >=1.2.0.
That's all just in my opinion. Feel free to make PR, Catalyst devs will be glad to review it and merge in case of success. Just don't forget to check codestyle :)

**Comment by TezRomacH** [comment]
@Podidiving thanks for reporting the bug and @Arquestro thanks for a quick and reasonable solution 😄 

> I guess it can be fixed with requirements rewrite. Just need to change the requirements to tensorboard>=1.14.0

Could you please provide a PR with this? 🙂

**Comment by Podidiving** [comment]
Thanks for respond!
I agree, it's better to fix tensorboard version
But still, I believe, that there are some people who use `catalyst` and `tensorflow` with version `<1.14.0` in their projects, and it's seems that compatibility issue can be solved with different import
Or it will be bad in terms of legacy support?

**Comment by Scitator** [comment]
Hi, for now let's hotfix with version requirements. Nevertheless, @Podidiving if you would like to contribute better support for older versions – it would be great.

**Comment by Arquestro** [comment]
Can be closed now, I guess. Gratz with first catalyst PR, @Podidiving!
