### ISSUE TITLE
Fixes required to run segmentation-tutorial.ipynb

### ISSUE THREAD

**Issue by adriangrepo** [catalyst-team/catalyst#562]
torch: 1.3.1, catalyst: 19.12.2

To get examples/notebooks/segmentation-tutorial.ipynb to train I made some modifications:

segmentation_models_pytorch api has changed since the nb was written, now need to do:

`

    import segmentation_models_pytorch as smp

    aux_params=dict(
        dropout=0.5,               # dropout ratio, default is None
        classes=1,                 # define number of output labels
    )

    # We will use Feature Pyramid Network with pre-trained ResNeXt50 backbone
    model = smp.FPN(encoder_name="resnext50_32x4d", classes=1, aux_params=aux_params)
`

To get tensorboard running in nb without error, need to load it:

`

    %load_ext tensorboard
    %tensorboard --logdir {logdir}
`

then in the catalyst codebase made the following hacks to get it to run:

catalyst.dl.callbacks.crtiterion.callbacks.py

`

    class CriterionCallback(...)

        def _compute_loss(self, state: RunnerState, criterion):
            output = self._get(state.output, self.output_key)
            input = self._get(state.input, self.input_key)
            if isinstance(output, tuple):    #added check
                output=output[0]
            loss = criterion(output, input)
            return loss
`

catalyst.dl.utils.criterion.iou.py

`

     def iuo(...)

        activation_fn = get_activation_fn(activation)
        if isinstance(outputs, tuple):    #added check
            outputs = outputs[0]
        outputs = activation_fn(outputs)
`

catalyst.dl.utils.criterion.dice.py

`

    def dice(...)

        activation_fn = get_activation_fn(activation)
        if isinstance(outputs, tuple):    #aded check
            outputs = outputs[0]
        outputs = activation_fn(outputs)

`
Then for inference another hack:

`

    class InferCallback(Callback):
        ....
        def on_batch_end(self, state: RunnerState):
            dct = state.output
            for key, value in dct.items():    #modified to add check for tuple
                if isinstance(value, tuple):
                    dct[key] = value[0].detach().cpu().numpy()
                else:
                    dct[key] = value.detach().cpu().numpy()
            for key, value in dct.items():
                self.predictions[key].append(value)
`

I am guessing there may be a more robust way of dealing with the tuple vs Tensor errors that apear pre-fixes above.

Pre fix tuple / Tensor error shown below:

/.../catalyst/dl/callbacks/criterion.py in _compute_loss(self, state, criterion)
---> 78         loss = criterion(output, input)
     79         return loss
     80 
     81     def on_stage_start(self, state: RunnerState):
     82         """

~/.virtualenvs/catalyst_base/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/.virtualenvs/catalyst_base/lib/python3.7/site-packages/torch/nn/modules/loss.py in forward(self, input, target)
    599                                                   self.weight,
    600                                                   pos_weight=self.pos_weight,
--> 601                                                   reduction=self.reduction)
    602 
    603 

~/.virtualenvs/catalyst_base/lib/python3.7/site-packages/torch/nn/functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   2109         reduction_enum = _Reduction.get_enum(reduction)
   2110 
-> 2111     if not (target.size() == input.size()):
   2112         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   2113 

AttributeError: 'tuple' object has no attribute 'size'

**Comment by TezRomacH** [comment]
Thank you for the feedback!

I removed AUX params for a while #566 to make the tutorial work, then we will think about how to avoid situations with `output[0]` because we do not always need the first element of the tuple.

**Comment by Scitator** [comment]
fixes by https://github.com/catalyst-team/catalyst/pull/566
