### ISSUE TITLE
Neptune support

### ISSUE THREAD

**Issue by jakubczakon** [catalyst-team/catalyst#570]
**Is your feature request related to a problem? Please describe.**
I want to create integration with the experiment tracking tool neptune.ml. 

**Describe the solution you'd like**
Almost exactly the same as [wandb logger](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/runner/wandb.py)

**Note**
Goes without saying that I will create this integration myself.

**Comment by TezRomacH** [comment]
done in #571
