### ISSUE TITLE
Frozen class implementation

### ISSUE THREAD

**Issue by ogvalt** [catalyst-team/catalyst#579]
**Describe the bug**

According to comment FrozenClass should prohibit change in existing attributes of coresponding instance. But if you look in the code below you could clearly see that it rather make unable to set new field to existing class dynamically. 
```
class FrozenClass:
    """
    Class which prohibit ``__setattr__`` on existing attributes
    Examples:
        >>> class RunnerState(FrozenClass):
    """
    __isfrozen = False

    def __setattr__(self, key, value):
        if self.__isfrozen and not hasattr(self, key):
            raise TypeError("%r is a frozen class" % self)
        object.__setattr__(self, key, value)

    def _freeze(self):
        self.__isfrozen = True
```

**To Reproduce**
1. state.epoch = 5 - allowed
2. state.random_new_assignment = 5
TypeError: <catalyst.dl.core.state.RunnerState object at 0x7f9a058a1f90> is a frozen class

**Expected behavior**
I expect certain clarification from team side to better understand what you are want to accomplish.

**Screenshots**
No screenshots

**Additional context**
-

**Comment by Scitator** [comment]
Yup, thats the logic - just create some object with predefined signature, so you can easily check what RunnerState consists of in one place. And to restrict user from untrackable behaviour like `state.random_new_assignment = 5` in the middle of training pipeline.

**Comment by ogvalt** [comment]
@Scitator I see, so its more about shallow freeze, rather that deep freeze. 
Btw, during my work on extending RunnerState with model_grads I found that it's possible for user to extend one with kwargs, which is great and clever trick to make it more flexible. But when it comes to actually extend RunnerState with custom fields, Runner abstract class lacks any possibility to pass any extention fields to RunnerState. So I'm going to fix this in next PR. 
If there is a need I could create separate GitHub Issue to track changes, or link my changes to this issue

**Comment by Scitator** [comment]
If I remember correctly, RunnerState can be easily extended through `state_params`:
config: https://github.com/catalyst-team/catalyst/blob/master/examples/configs/config-description-eng.yml#L71
src: https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/core/runner.py#L96

**Comment by ogvalt** [comment]
Yes, you're correct. I've searched for this, but didn't found. Thanks.

**Comment by Scitator** [comment]
Thats great!
