### ISSUE TITLE
Bug with default input and output keys

### ISSUE THREAD

**Issue by smivv** [catalyst-team/catalyst#584]
As far as I understood, criterion module is wrapping now with CriterionCallback.
But the problem is that in CriterionCallback there is a default output_key='logits', and if I have no 'logits' in my outputs of neural net, I receive an error ```KeyError: 'logits'```.

To reproduce it you just need to set output_key to something that does not contain 'logits'.
Also the same thing we have for 'features' key for inputs.

Link to discussion on slack: https://opendatascience.slack.com/archives/CGK4KQBHD/p1578479340006900

**Comment by smivv** [comment]
Hmm, somehow input_target_key arguments fixed this problem 🤔

**Comment by smivv** [comment]
By the way, the bug still remains.

If I set ```output_key=None``` for Runner and return dict from model I got ```KeyError: 'logits'```.

**Comment by smivv** [comment]
Seems like I got why do I have that error - https://github.com/catalyst-team/catalyst/blob/f909e5b44eb4c2c26039e201bcbe67001529a515/catalyst/dl/experiment/config.py#L535

Seems like catalyst loads CriterionCallback by default for some reason while I am also using CriterionCallbacks.

**Comment by ValentinKoch** [comment]
How did you fix it? Still happening to me..
