### ISSUE TITLE
Doubts to open segmentation mask

### ISSUE THREAD

**Issue by BrunoKrinski** [catalyst-team/catalyst#587]
Hi, first of all, awesome framework. I work with segmentation and it's really hard to find a good segmentation framework.

I'm following the segmentation tutorial of the provided colab: [segmentation-tutorial.ipynb](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb) and I'm creating the SegmentationDataset class to open my images. 

So, I have a doubt about how to open my segmentation masks. The datasets I'm working on have .png grayscale masks, with each pixel value corresponding to a category of my problem. 

My doubt is if I should convert the mask to one hot, returning an nd array of dimension [w, h, num classes, batch size] or should just to open the mask and return it. 

Thanks!

**Comment by ogvalt** [comment]
Pytorch uses channel first approach, so each image encoded in CWH format, or BCWH for batch of images. Therefore segmentation model output also in BCWH and your ground truth should be in BCWH.

**Comment by Scitator** [comment]
yup, following the PyTorch you need BCHW tensor
