### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [catalyst-team/catalyst#6]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

**Comment by Scitator** [comment]
Hi, 

Thanks for suggestion. Definitely, it's one of  MUST things to do ASAP (just after docs 😄).
I will try to do something like that by myself or ask for community support (cause I have no experience at such stuff) soon.

Nevertheless, you always can PR for such great things - just ping me if you want to make this lib better.

**Comment by cclauss** [comment]
If you pick one of the three and then I will submit a pr.

**Comment by Scitator** [comment]
That's great!
From my experience, I usually see Travis CI as a test&deploy service. So, let's try it here too.

By the way, several suggestions, that I think can help with this stuff:
1. As prometheus isn't a lib and works as submodule, the best way to test it - use its' [examples](https://github.com/Scitator/prometheus-examples) as main "lib" project. At least I think so. 
2. From my point of view, [ray](https://github.com/ray-project/ray) lib is one with good CI, tests and docs organisation. Again, I am not an expert in this things, but look quite promising. 

And thanks for support!

**Comment by Scitator** [comment]
solved by https://github.com/Scitator/prometheus/pull/7
