### ISSUE TITLE
Documentation on Criterion

### ISSUE THREAD

**Issue by cgarciae** [catalyst-team/catalyst#619]
Is there documentation on how to setup a `criterion` in the `SupervisedRunner` to deal with complex loss functions for models with multiple labels and multiple outputs, especially for cases that their relation is not 1-to-1, e.g. using 3 labels and 2 outputs to define the loss.

**Comment by Scitator** [comment]
Yeah, sure!
Check out our [segmentation tutorial](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb).
