### ISSUE TITLE
Config with dependencies

### ISSUE THREAD

**Issue by AndreySheka** [catalyst-team/catalyst#624]
The main idea is one config - one experiment. Some experiments may have common parts. Now this is implemented in the form of passing a list of configs to `catalyst-dl run`. But this is difficult for new people to understand. It is suggested to add the `pre-configs` and `post-configs` fields to the config, which will be converted to the config list when the experiment is started. This should make it easier to understand.

**Comment by Scitator** [comment]
Why do you need to store information about configs in the config? It looks a bit unclear, is there any usecase for this issue?

**Comment by AndreySheka** [comment]
It's like inheriting classes. For example, experiments with different network architectures may have the same data preprocessing. Variations with stages are also possible. Combining several configs via the command line is easy to get confused. Moreover, the presence of one config is easier to explain and it is more intuitive, because a person understands what dependencies this config has and can find all the parameters of the experiment that interest him.

**Comment by Scitator** [comment]
Looks like, we really need to think more about hydra configs integration.
