### ISSUE TITLE
runner_params cannot be found in _config.json

### ISSUE THREAD

**Issue by fursovia** [catalyst-team/catalyst#632]
**Describe the bug**
`catalyst-dl run` doesn't save `runner_params` to `logs/configs/_config.json` file.

@TezRomacH could you help please?

**Comment by TezRomacH** [comment]
Hi, thanks for the report. Yeap, i'm working on the solution.

**Comment by TezRomacH** [comment]
The solution is here: https://github.com/catalyst-team/catalyst/pull/633

**Comment by TezRomacH** [comment]
merged, the solution will appear in the next micro release
