### ISSUE TITLE
RMS Normalization

### ISSUE THREAD

**Issue by avinashsai** [catalyst-team/catalyst#637]
**Is your feature request related to a problem? Please describe.**
RMS Normalization https://openreview.net/pdf?id=SygkZ3MTJE is a normalization technique proposed for normalizing CNN and LSTM.

**Describe the solution you'd like**
I have experimented Layer Normalization and RMS Normalization using LSTM on IMDB dataset. Experiment results can be found here: https://github.com/avinashsai/All-you-need-to-know-about-Normalization/blob/master/Experiments/Normalization_IMDB.ipynb. I would like to include this normalization technique in the framework. Please share your thoughts on this. 

Thank you

**Comment by avinashsai** [comment]
@Scitator Please share your thoughts on this.

**Comment by Scitator** [comment]
Hi @avinashsai,
Thanks for your proposal, we are definitely would be grateful for your contribution,
you can add your implementation to [https://github.com/catalyst-team/catalyst/tree/master/catalyst/contrib/nn/modules/rms_norm.py](https://github.com/catalyst-team/catalyst/tree/master/catalyst/contrib/nn/modules) for example :)

**Comment by avinashsai** [comment]
Thank you. will surely work on it.
