### ISSUE TITLE
Center Loss

### ISSUE THREAD

**Issue by smivv** [catalyst-team/catalyst#646]
I think it's time to implement also center loss :)

Center Loss: https://ydwen.github.io/papers/WenECCV16.pdf
Implementations: [1](https://github.com/KaiyangZhou/pytorch-center-loss/blob/master/center_loss.py), [2](https://github.com/louis-she/center-loss.pytorch/blob/master/loss.py), [3](https://github.com/SWHL/pytorch-center-loss/blob/master/center_loss.py), [4](https://github.com/jxgu1016/MNIST_center_loss_pytorch/blob/master/CenterLoss.py)

**Comment by Scitator** [comment]
@smivv would you like to make a contribution?

**Comment by Scitator** [comment]
already implemented
