### ISSUE TITLE
Bug with trace_model when runner's process_input is process_input_list

### ISSUE THREAD

**Issue by Podidiving** [catalyst-team/catalyst#648]
**Describe the bug**
In `trace.trace_model` model is wrapped in `_TracingModelWrapper` class, which return `None` after
`forward` method is called. This is the reason of issue, when `runner.predict_batch()` method is called 

**Steps to reproduce the behavior**
There is a simple example to invoke this error

![image](https://user-images.githubusercontent.com/26285240/74075425-69f20180-4a23-11ea-8f97-bc84480ea730.png)
![image](https://user-images.githubusercontent.com/26285240/74075485-9efe5400-4a23-11ea-877f-e03b8678b583.png)
![image](https://user-images.githubusercontent.com/26285240/74075489-a58ccb80-4a23-11ea-8475-909291f62850.png)

**Additional context**
Duck tape approach to fix this bug - to return `model(*args, **kwargs)` in `_TracingModelWrapper` method

**Comment by TezRomacH** [comment]
Is the bug still exist if using `runner.trace(**params)`?

**Comment by Podidiving** [comment]
@TezRomacH , yes, still the same issue, because the same function `trace_model` is called inside runner

**Comment by Scitator** [comment]
Fixed :)
