### ISSUE TITLE
optimize model grads collections

### ISSUE THREAD

**Issue by ogvalt** [catalyst-team/catalyst#655]
**Is your feature request related to a problem? Please describe.**
I've work with my recent approach to collecting model gradients and find out that is not that optimal (#576 #581 ). 
The main problem is that I need to initialize optimizer in my code with flag save_model_grads an then pass it in callback list. eg:

```
# train.py
optimizer_with_grad_collection = OptimizerCallback(save_model_grads=True)
...
runner.train(...
callbacks = [
optimizer_with_grad_collection,
...
],
)
```
(Also I found that the way that is used to collecting gradients slows down model training and I've already prepared faster solution)

**Describe the solution you'd like**
I want to rollback some changes that I've done and make everything looks like this:
```
# train.py
runner.train(
state_kwargs = {"model_grads": {}}
...
)
# optimizer.py
class OptimizerCallback(Callback):
...
def on_batch_end(self, state):
...
if hasattr(state, "model_grads"):
   # collect grads
```

**Comment by Scitator** [comment]
looks like done, isn't it?
