### ISSUE TITLE
Enhance wandb runner with wandb.watch and log custom step

### ISSUE THREAD

**Issue by ogvalt** [catalyst-team/catalyst#656]
**Is your feature request related to a problem? Please describe.**
So the ideas here is next:
1. wandb has good solution for tracking gradients of the model via wandb.watch(model). 
2. wandb logs information about the model with respect to steps. Ones increasing each time user call wandb.log(...). Sometimes it's quite confusing when train and valid data don't co-aling in terms of steps.

**Describe the solution you'd like**
1. extend _pre_experiment_hook like:
```
class WandbRunnerV2(WandbRunner):
...
def _pre_experiment_hook(self, experiment: Experiment):
        super(WandbRunnerV2, self)._pre_experiment_hook(experiment)
        model = self.model
        wandb.watch(model)
```
2. I would like to add additional field to log in wandb runner: _epoch for log on each epoch. I've checked that in wandb UI I'm able to set custom axis for visualization.

**Comment by Scitator** [comment]
done
