### ISSUE TITLE
Refactoring of Runner._run_event and _State

### ISSUE THREAD

**Issue by Arquestro** [catalyst-team/catalyst#670]
Several interconnected problems here:

1. `metric_manager` is a part of `_State` functionality. The only reason for `_State` to have pre/post methods. Partly that makes `_State` behaviour to look like a Callback one, but with own set of events.
2. `Runner._run_event` is too complicated: too many "if"-statements and `moment` argument is not needed, due to the fact that we can make `event` for every moment and there is no frequent need in extraction of the moment from the event.

This can be done in the following way:
1. Metric manager can be done as callback and `_State` pre/post and metric handling methods deleted.
2. With deletion of pre/post methods from the `_State` we can clean up "if"-statements in `Runner._run_event`. The only reason we'll need to have if statements is to figure out order of callbacks and loggers. "Moments" can be concatenated with "event" in the following way: `{event}_{moment}` to get rid of moments. [Gist example](https://gist.github.com/Arquestro/08782eae0c68c7c4bd80d38327f009c0)

Alternative solution to 2 includes making a dict with events as keys and proper OrderedDict of callbacks and loggers as values for every stage. This is a bit ugly, but it will help to get rid of "if"-statements. [Gist example](https://gist.github.com/Arquestro/6374b4dd739e591422029828e7c04c2b)

**Comment by Arquestro** [comment]
Too much functionality is on `metric_manager`, won't be that easy to get rid of to in one take. I think that it will be okay to begin with p.2 but with processing state pre/post methods for now in callbacks event preparing, temporary solution.

After that task is done we can make `metric_manager` refactoring, with `_State` cleaning of metric handling and enhancing functionality with addition of MetricManagerCallback.

**Comment by Scitator** [comment]
Done, during  `20.03` release
