### ISSUE TITLE
When using an activation function of "Softmax2d" for many callbacks and losses, no argmax is applied

### ISSUE THREAD

**Issue by jchen42703** [catalyst-team/catalyst#682]
# (I will compile a list and hopefully open a PR if needed)

**Describe the bug**
This behavior is present in a plethora of catalyst's callbacks and losses. It's consistent, but it's definitely confusing for many new users.

**To Reproduce**
Use these functions/classes:
Callbacks
* [`MeterMetricsCallback`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/core/callback.py)
  * I'm not sure if this can support meters with softmax? Need to double check

Criterion // Dependents
* [`dice`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/criterion/dice.py)
  * [`DiceCallback`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/metrics/dice.py)
  * [`DiceLoss`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/nn/criterion/dice.py)
* [`f1_score`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/criterion/f1_score.py)
  * [F1ScoreCallback](https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/callbacks/metrics/f1_score.py)
* [`iou`](https://github.com/catalyst-team/catalyst/blob/a7154b8d37b7368f6984c23df309069d22cd32fd/catalyst/utils/criterion/iou.py#L9)
  * [`IoULoss`](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/nn/criterion/iou.py)
  * [`IouCallback`]()

**Expected behavior**
Should ideally apply argmax when `activation='Softmax2d'`

**Screenshots**

**Additional context**

**Comment by Scitator** [comment]
Do you have a minimal example to reproduce the issue?

**Comment by Scitator** [comment]
Dear @jchen42703 ,
How are you doing? Does this issue is still valid? Do you have a proposal for a Pull Request contribution?

**Comment by jchen42703** [comment]
@Scitator Ahhhh sorry, I've been prioritizing work lately. I'll hopefully get to this by the end of next week. I think the PR should just be a warning for the next version and then the actual changes on the version after that.

**Comment by Scitator** [comment]
@jchen42703 Thank you!

**Comment by Scitator** [comment]
Dear @jchen42703 ,
Do you have any plans for this feature implementation? 
Thanks in advance.

**Comment by Scitator** [comment]
@jchen42703  👀  :)
