### ISSUE TITLE
Reassessing Visdom Support

### ISSUE THREAD

**Issue by Entodi** [catalyst-team/catalyst#692]
I have a solution for visdom support (https://github.com/facebookresearch/visdom) which was pointed out here in closed issues (https://github.com/catalyst-team/catalyst/issues/344).

I implemented:
-  VisdomLogger based on alchemy.logger (https://github.com/catalyst-team/alchemy/blob/master/alchemy/logger.py)
- VisdomRunner and SupervisedVisdomRunner based on AlchemyRunner (https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/dl/runner/alchemy.py)

![image](https://user-images.githubusercontent.com/2220676/76134146-48684380-5fea-11ea-896b-33c51b718850.png)

**Comment by Scitator** [comment]
Thanks for noting,
would you like to make a pull request on this feature?
