### ISSUE TITLE
text2embedding bug

### ISSUE THREAD

**Issue by elephantmipt** [catalyst-team/catalyst#700]
When I tried to get embeddings from my text via `catalyst-data text2embedding` I got this error:

![image](https://user-images.githubusercontent.com/37884009/76395460-676b2a80-6388-11ea-806f-70c328704901.png)

Probably lines 145 and 146 in `catalyst/data/scripts/text2embedding.py` should be

```
                hidden_size=model.module.config.hidden_size,
                output_hidden_states=model.module.config.output_hidden_states,
```

instead of

```
                hidden_size=model.config.hidden_size,
                output_hidden_states=model.config.output_hidden_states,
```

pytorch version: 1.4.0

**Comment by Scitator** [comment]
Thanks for noting,
Would you like to make a pull request to resolve the issue?

**Comment by Scitator** [comment]
fixed :)
