### ISSUE TITLE
Training without storing model states

### ISSUE THREAD

**Issue by ditwoo** [catalyst-team/catalyst#705]
**Description**
In some rare cases, for example, when you need to finetune a large model on a small dataset the majoring part of training loop is waiting for saving model checkpoints to a hard drive.

**Proposal**
Would be logically to add a `CheckpointCallback` with parameter `save_n_best=0` to a configuration and do not store best checkpoints and instead use the latest state of the model.

**Note**
All of the described above is a proposal mostly for **config API** because **config API** during the stages loads the best checkpoint from the previous stage.

So here are a few steps to how it can be achieved:
1. For using the latest state of the model you need to overload a `get_model` property of `ConfigExperiment` to return the latest model (something like in `BaseExperiment`).
2. To prevent saving the model state to a hard drive overload property `get_callbacks` of experiment class and remove `CheckpointCallback ` from default callbacks.
3. Create and use an empty callback instead of `CheckpointCallback`.

**Comment by Scitator** [comment]
Dear @Ditwoo,
could you please make a Pull Request with such functionality?

**Comment by Scitator** [comment]
🤔 Isn't is done already?

**Comment by ditwoo** [comment]
@Scitator yep, seems like it's already [impemented](https://github.com/catalyst-team/catalyst/pull/797).
