### ISSUE TITLE
dice metric

### ISSUE THREAD

**Issue by vsokhatskyi** [catalyst-team/catalyst#725]
catalyst/utils/metrics/dice.py
`dice = 2 * (intersection + eps * (union == 0)) / (union + eps)`

It seems like if union = 0 and intersection = 0, we get  dice = 2 * (0 + eps) / (0 + eps) = 2 ?

Should be 
`dice = (2 * intersection + eps * (union == 0)) / (union + eps)`
or I don't understand something?)

**Comment by Arquestro** [comment]
I agree on this :) That one boundary point is essential in case you have empty target mask.
![image](https://user-images.githubusercontent.com/7341001/77687991-60f7c800-6fb0-11ea-8fd8-97d1834386e5.png)

**Comment by Scitator** [comment]
Wow, thank you @vsokhatskyi  for you findings!
Would you like to make a PR to handle this issue? It would be great.

**Comment by vsokhatskyi** [comment]
@Scitator, ok, I'd like to make PR to handle this issue.

One more question. 
For what reason we use eps?) 

What if we use something like this: 
`dice = (2 * intersection + (union == 0)) / (union + (union == 0))` ?

**Comment by Scitator** [comment]
fixed :)
