### ISSUE TITLE
OOM during validation step using multiple GPUs

### ISSUE THREAD

**Issue by ai-niki** [catalyst-team/catalyst#733]
**Describe the bug**
4x GPU memory consumption raise during validation causes OOM. Have to decrease BS to BS/2 to run without errors. This happens only in a multi-GPU setup (we have 4).

**To Reproduce**
1. ...

**Expected behavior**
Using less memory during validation.

**Screenshots**
![photo_2020-03-31 12 12 03](https://user-images.githubusercontent.com/18504735/78008881-e67cce80-7348-11ea-8ac5-d9297af0f20f.jpeg)

**Additional context**
Similar to this: https://github.com/catalyst-team/catalyst/issues/143

**Comment by Scitator** [comment]
Does this issue still valid? Do you have plans for a Pull Request?

**Comment by ai-niki** [comment]
Looks like it’s fixed in a new version

**Comment by Scitator** [comment]
not sure if we have done anything 😂
