### ISSUE TITLE
Catalyst.DL breaks Albumentations/Numpy

### ISSUE THREAD

**Issue by bradezard131** [catalyst-team/catalyst#741]
**Describe the bug**
If `catalyst.dl` is imported, Albumentations will not work due to errors along the line of `numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject`

**To Reproduce**
1. Create new Python 3.7 environment
2. `pip install -U catalyst` or `pip install catalyst[all]`
3. `import catalyst.dl`
4. Run the code from the Augmentations cell in the classification tutorial

**Expected behavior**
No errors, should work

**Additional context**
I created and destroyed multiple environments trying to fix this. OS is Ubuntu 18.04.3 server

**Comment by Scitator** [comment]
@bradezard131 Could you please provide an example?
Tested with several pipelines, no errors found.

**Comment by ngxbac** [comment]
@Scitator , I got the same problem as well. However, it is just warning. The albumentation still works

**Comment by Scitator** [comment]
Thanks!
I knew about warning, but have not seen any albumentations incompatibilities.

**Comment by Scitator** [comment]
closing for now
