### ISSUE TITLE
TypeError: _open() got an unexpected keyword argument 'as_gray'

### ISSUE THREAD

**Issue by andrew12678** [catalyst-team/catalyst#751]
**Describe the bug**
I pretty much followed the [classification tutorial](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/classification-tutorial.ipynb) and changed the dataset to my own dataset and I receive an `imread` error of similar nature to a very old issue [#472 ](https://github.com/catalyst-team/catalyst/issues/472)
 
```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/catalyst/data/dataset.py", line 50, in __getitem__
    dict_ = self.open_fn(item)
  File "/usr/local/lib/python3.6/dist-packages/catalyst/data/reader.py", line 251, in __call__
    for fn in self.readers:
  File "/usr/local/lib/python3.6/dist-packages/catalyst/data/reader.py", line 79, in __call__
    img = imread(
  File "/usr/local/lib/python3.6/dist-packages/catalyst/contrib/utils/image.py", line 73, in imread
    # @TODO: add tiff support, currently – jpg and png
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'as_gray'
```

**To Reproduce**
I have cloned notebook which should download my dataset [here](https://colab.research.google.com/drive/101lnX-MHKaDsH7_qDC0s8p_cHVq0ZLiq) and should replicate the issue.

**Expected behavior**
It should start outputting the Epoch's Accuracies etc just like example Artist dataset should.

**Comment by bagxi** [comment]
Hi,
Could you please check if everything will be fine with `imageio<2.5.0`?

**Comment by andrew12678** [comment]
@bagxi Problem still persists with imageio==2.2.0 and imageio==2.3.0 (just tried in my colab notebook that I linked)

**Comment by Scitator** [comment]
could you please check, if an error still occurs with only jpg/png dataset?

**Comment by YaLTeR** [comment]
This error disappears if you replace multiple pip installs in the second cell with a single one: `!pip install -U albumentations pretrainedmodels catalyst tensorflow`

**Comment by andrew12678** [comment]
@Scitator I've checked all the images using ImageMagick by converting everything to JPG if they weren't already JPG

@YaLTeR Unfortunately I still get the error in the notebook with that particular change

**Comment by lokeshkvn** [comment]
@Scitator @YaLTeR @andrew12678 I am also getting the same error '_open() got an unexpected keyword argument 'as_gray'. Any temporary fix for now?

**Comment by lokeshkvn** [comment]
@Scitator @bagxi @andrew12678 I found out that this error occurs when our image is in `GifImageFile` format. Even if the extension of the file is ***.jpg*** the file format is different sometimes while reading the files. 
The temporary fix for this issue is Instead of calling ```utils.imread``` in _dataloaders/Augmentaions/show()_ while creating and initializing `Dataset ` and we can use `PIL.Image.open('filename').convert('RGB')` which handles all types of files

**Comment by Scitator** [comment]
@lokeshkvn yup, `utils.imread` is mostly focused on typical image formats, like `.jpg`, `.png` etc.
For `.tiff`, `.gif` - you can try to use `utils.mimread` instead :)
Nevertheless, PR with appropriate docs (that you find clear to use and read) would be really welcome, thanks in advance!
