### ISSUE TITLE
AttributeError: module 'catalyst.utils' has no attribute 'detach' while running Segmentation Tutorial

### ISSUE THREAD

**Issue by faizankshaikh** [catalyst-team/catalyst#758]
**Describe the bug**
When I run the [tutorial on Segmentation](https://github.com/catalyst-team/catalyst/blob/master/examples/notebooks/segmentation-tutorial.ipynb), with little to no change from my side, I get the error AttributeError: module 'catalyst.utils' has no attribute 'detach' when I try to run the second cell in "Model Inference" of the notebook

**To Reproduce**
Run the notebook of Segmentation Tutorial on Colab and follow along with the steps

**Expected behavior**
The cell should show predictions from the model, i.e. image with the respective mask

**Screenshots**
![catalyst_issue](https://user-images.githubusercontent.com/8406903/79645081-b9467200-81ca-11ea-9365-d4de96082f24.png)

**Comment by faizankshaikh** [comment]
Resolves if I add function before the cell is run and replace `utils.detach` with `_detach`
```
def _detach(tensor):
    return tensor.cpu().detach().numpy()
```

Can submit a PR by tomorrow if required. Found the solution [hidden deep](https://github.com/catalyst-team/catalyst/blob/2ede5354b2a02807b3c1c69fc0718351382c8301/catalyst/data/scripts/text2embedding.py#L104) in the code

**Comment by Scitator** [comment]
Yeah sure, could you please add `detach` method to https://github.com/catalyst-team/catalyst/blob/master/catalyst/utils/torch.py ?

**Comment by faizankshaikh** [comment]
Done https://github.com/catalyst-team/catalyst/pull/766
