### ISSUE TITLE
GAN example doesn't converge

### ISSUE THREAD

**Issue by MalchuL** [catalyst-team/catalyst#759]
**Describe the bug**
On master (according catalyst==20.4.1) (https://github.com/catalyst-team/catalyst/commit/abfb121640e6934c99210e9c0f402af5338200c8) GAN example can't converge.
I use this example https://github.com/catalyst-team/catalyst/tree/master/examples/mnist_gans. I run next script `catalyst-dl run --config=./mnist_gans/configs/vanilla_gan.yml --verbose`. After 100 epoches I had next loss values:
loss_d=0.5493 | loss_d_fake=**1.0986** | loss_d_real=**1.526e-06** | loss_g=0.4054

**Expected behavior**
On old version (20.2) in this repo (https://github.com/catalyst-team/gan) I got next
losses | loss_d_fake < **0.5** | loss_d_real < **0.5** | 

**Additional context**
I found that behavior starts since catalyst 20.3 version

**Screenshots**
After training on catalyst==20.4.1 in tensorboard I got this images 
![Screenshot from 2020-04-19 20-44-51](https://user-images.githubusercontent.com/22708053/79695295-b9a04500-827e-11ea-89bc-9cde66528904.png)

**Comment by Scitator** [comment]
Please move this issue to our Catalyst.GAN repo, https://github.com/catalyst-team/gan
