### ISSUE TITLE
"not_basic" check in VerboseLogger has a spelling mistake?

### ISSUE THREAD

**Issue by YaLTeR** [catalyst-team/catalyst#772]
**Describe the bug**
This checks for the `_timers` prefix:
https://github.com/catalyst-team/catalyst/blob/fbd7d0e78f673707df7d6375423fe02da619b398/catalyst/core/callbacks/logging.py#L47
However the default timer callback has a `_timer` prefix, not `_timers`, and there's nowhere else where the `_timers` string is mentioned. Effectively, this always shows all timer metrics in VerboseLogger, rather than just `_timer/_fps` as seems intended judging by the default value of the `always_show` argument.

**Comment by Scitator** [comment]
@YaLTeR good catch!
This looks like so, thank you!
Is it possible for you to create a small PR with typo fix?

**Comment by YaLTeR** [comment]
Sure.
