### ISSUE TITLE
list of implemented papers

### ISSUE THREAD

**Issue by bagxi** [catalyst-team/catalyst#783]
## 📚 Documentation

> было бы не плохо добавить в доку страничку со ссылками на все статьи из которых мы что-то реализовали
> наверное, так даже будет чуть проще пиариться среди академиков

*source: catalyst-slack*

**Comment by Scitator** [comment]
Do you mean reorganize our https://github.com/catalyst-team/catalyst#projects ?

**Comment by bagxi** [comment]
no,
in my opinion, adding "papers list" page to https://catalyst-team.github.io/catalyst/ will be enough

**Comment by Scitator** [comment]
for now, I have reorganised https://github.com/catalyst-team/catalyst#paper-implementations
Documentation page - work in progress with "gpus4research initiative"
