### ISSUE TITLE
Metric learning

### ISSUE THREAD

**Issue by AlekseySh** [catalyst-team/catalyst#787]
## 🚀 Feature Request
It would be great to have **metric learning pipeline** in Catalyst. The goal of metric learning is to get the model that can map some objects into vector space where similar objects will have close representation and different objects will have far representations. The typical example is the person reidentefication task - [reid](https://paperswithcode.com/task/person-re-identification). 

Now we only have several triplet loss implementations in
[contrib](https://github.com/catalyst-team/catalyst/blob/f58ffac876f514f3b52537d62b5c81b562a93fa9/catalyst/contrib/nn/criterion/triplet.py). But there are a lot of missing puzzle details like:
* `Sampler` that can sample batches with both positive and negatives examples in sufficient quantity.
* `TripletSelector` hat can provide politics for triplets selection: all triplets, hard triplets, k-hardest triplets and so on.
* `RetrievalMetric` (like `cmc-score`) that can evaluate the model: usually it is calculated after splitting validation dataset into query and gallery parts.
and so on

It would be great to see all of this as a consistent framework.
As datasets for debugging and example we can use: [omniglot](https://github.com/brendenlake/omniglot) (objects are symbols) or [mars](http://www.liangzheng.com.cn/Project/project_mars.html) (objects are people) or any other suitable dataset. 

Alternative for reid: [deep reid](https://kaiyangzhou.github.io/deep-person-reid/) library.

**Comment by Scitator** [comment]
Hi @AlekseySh ,
Honestly speaking, we already have a few Metric Learning experiments with @PUSSYMIPT :)

Nevertheless, let's discuss your proposal a bit more. What samplers and metrics would you like to implement?

**Comment by AlekseySh** [comment]
Discussed on the call.

Next step: prepare proposal with @PUSSYMIPT

**Comment by Scitator** [comment]
@stale nope :)

**Comment by Scitator** [comment]
okay, now looks like it's done :)
