### ISSUE TITLE
How to use 4-channel image in ImageReader

### ISSUE THREAD

**Issue by KanchanIIT** [catalyst-team/catalyst#795]
My input images are 4-channel images. the default ImageReader only loading the first 3-channel (RGB) of the image. ImageReader has the option for grayscale, but can we load the n-channel images using ImageReader?
Thanks a lot for your help.

**Comment by bagxi** [comment]
Hi!
Can you try [LambdaReader](https://github.com/catalyst-team/catalyst/blob/master/catalyst/data/reader.py#L100) for this purpose? e.g.
```
image_reader = LambdaReader(function_to_load_4ch_image)
```
