### ISSUE TITLE
Parameter "device" in SupervisedRunner has no effect

### ISSUE THREAD

**Issue by yhn112** [catalyst-team/catalyst#798]
## 🐛 Bug Report
When running with `device=torch.device('cuda:0')` or  `device='cuda:0'` model still uses all the GPUs.
When running with `device=torch.device('cpu')` or  `device='cpu' an` error `RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu` appears.

### How To Reproduce
Run any sort of training using `SupervisedRunner(device=torch.device('cpu'))` or `SupervisedRunner(device=torch.device('cuda:0'))` on a machine with multiple GPUs.

### Environment
```Catalyst version: 20.05
PyTorch version: 1.5.0
OS: Ubuntu 18.04
Python version: 3.7
CUDA runtime version: 10.2```

**Comment by AlekseySh** [comment]
I faced with the same problem

**Comment by AlekseySh** [comment]
You can use `CUDA_VISIBLE_DEVICES` as work around

**Comment by yhn112** [comment]
I certainly do use `CUDA_VISIBLE_DEVICES`. It doesn't help me deal with such severe bugs in such a popular framework. =)

**Comment by yhn112** [comment]
I'm sorry to do that, but
ping @Scitator 
how do you do? =)

**Comment by Scitator** [comment]
@yhn112 please, check the hotfix :)
https://github.com/catalyst-team/catalyst/pull/815

**Comment by Scitator** [comment]
now, it's your turn 😂 
https://github.com/catalyst-team/catalyst/pull/809
