### ISSUE TITLE
Mistake in averaging of total epoch loss 

### ISSUE THREAD

**Issue by AlekseySh** [catalyst-team/catalyst#799]
It looks like that averaging of the loss values (while calculating total epoch loss) does not take into account the size of the batch.
Thus, in situations when the last batch is smaller than the required size (if the size of the dataset is not divisible by the size of the batch), it still enters the average with the same weight as all other batch.

This also applies to metrics and other quantities.

**Comment by yhn112** [comment]
Sorry for my importunity, but I have to say that it's a good reason to add a sample counter, as I suggested in https://github.com/catalyst-team/catalyst/issues/755#issuecomment-626059081 =)

**Comment by Scitator** [comment]
Agreed, thanks for noting.
Due to https://www.github.com/catalyst-team/catalyst/blob/master/catalyst/core/runner.py#L386#L389 we have correct per-loader `batch_size`, but have don't have correct non-`drop_last` loader handling.

PR would be appreciated :)

**Comment by yhn112** [comment]
But how is it reasonable to do this from an "architectural" point of view?
In my opinion, `state.batch_size` reflects the loader property and should not be changed during the loader operation. So I would add `state.current_batch_size` separately and would like to have something like this:
```
def _run_batch(self, batch: Mapping[str, Any]) -> None:
        self.state.current_batch_size = batch.shape[0]
        self.state.global_step += self.state.current_batch_size
        batch = self._batch2device(batch, self.device)
        self.state.input = batch

        self._run_event("on_batch_start")
        self._handle_batch(batch=batch)
        self._run_event("on_batch_end")
        self.state.current_batch_size = None  # to show that it makes no sense outside handling a batch
```

**Comment by Scitator** [comment]
I think, that `batch_size` property should be with `current_batch_size` logic. And if you and `current_loader_batch_size` it's better to use something like `state.loader_batch_size`.
