### ISSUE TITLE
Fail to get Transform function

### ISSUE THREAD

**Issue by baibaidj** [catalyst-team/catalyst#803]
## 🐛 Bug Report

I think a bug exists here https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L415. 
So the line "elif not isinstance(transform, AugmentorCompose)" is trying to check if the "transform" function generated is a AugmentorCompose object. When I use the transform.yml provided in _test_cv_segmentation, the resulting transform is in fact a Compose object and will be judged as NOT AugmentorCompose. Finally the returning transform cannot accept the dict with 'image' and 'mask' keys as input, thus leading to error. Without this judgment (e.g. removing the not), the transform will behave as anticipated.

### How To Reproduce
1. Go to https://github.com/catalyst-team/catalyst/tree/master/tests/_tests_cv_segmentation
1. Run the training script with the transform.yml in the folder. 
3. you should be able to encounter the error. 

 

#### Code sample
this code is in the tests folder.

#### Screenshots

![屏幕快照 2020-05-12 下午7 07 27](https://user-images.githubusercontent.com/24452296/81765596-d12dbf00-9506-11ea-8e01-436f9bff7700.png)
![屏幕快照 2020-05-12 下午7 07 43](https://user-images.githubusercontent.com/24452296/81765637-f28eab00-9506-11ea-81c7-9624db69b315.png)

### Expected behavior
get a transform function (Compose object from albumentation) that can accept a dict with 'image' and 'mask' keys as input and do the transformation as indicted in the transform.yml. 

### Environment
Catalyst version: 20.05
PyTorch version: 1.1.0
TensorFlow version: 2.2.0
TensorBoard version: 2.2.0
OS: Ubuntu 16.04.3 LTS
Python version: 3.6
CUDA runtime version: Could not collect
Nvidia driver version: 387.26
cuDNN version: Could not collect

**Comment by Scitator** [comment]
@bagxi what do you think about this case?

**Comment by bagxi** [comment]
Could you please describe what do you mean by a bug?

There are two layers of `_key_value` in the `get_transforms` function. And in each case logic is a little bit different:
1. If `transform_params` isn't defined in the config, then the output will be an identity function. See https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L412 for details.
2. The first key is `False` e.g.
    ```
    transform_params:
      transform: albumentation.Compose
      transforms: [list of amazing image-mask transforms]
    ``` 
    The same transform will be used for all data loaders. `albumentation` transforms expects that the input will be passed as key-value (`transform(image=image, mask=mask)`) and by default dataset return dicts. That's why we wrap transform with the helper function that will unpack dict for us. See https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L418 for details.
3. The first key is `True`, the second is `False` -> similar to 2. but for each loader, the custom transform can be applied. See https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L407 for details.
4. The first key is `True`, the second is `True`, e.g.:
    ```
    transform_params:
      _key_value: True
      train:
        _key_value: True
        image:
          transform: albumentation.Compose
          transforms: [list of amazing image transforms]
        mask:
          transform: albumentation.Compose
          transforms: [list of amazing mask transforms]
    ``` 
    Transform of each key of each sample is independent. To handle this logic so we added `AugmentorCompose` abstraction. Input for `AugmentorCompose` is dict, so there is no need to wrap transform with helper function as in 2. and 3. See https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/experiment/config.py#L412 for details.

So, could you check the implementation of your dataset?

**Comment by baibaidj** [comment]
Thank you for the elaborate explanation. I may need more time to make sense of it. 

In my testing, the transform.yml configuration falls into the 3rd category `True` for the first key and `False` for the second. The specifics is like this :
```
transform_params:
    _key_value: True
    train:
      transform: A.Compose
      transforms:
        - transform: A.SmallestMaxSize
          max_size: *resize_size
          p: 1.0
```

I implemented my dataset like this:
```
    def __getitem__(self, idx: int) -> dict:
        """Main method"""
        img_path = self.images[idx]
        image = open_image_multi_channel(img_path, channel= 3)
        mask = open_mask_random(self.masks[idx])
        result = {'image': image}
        # extract certain classes from mask (e.g. cars)
        if self.label_mapping is not None:
            mask = convert_label(mask, self.label_mapping)
        result['mask'] = mask
        if self.transforms:
            result = self.transforms(**result) # ablu.transform 可以对2d mask 进行操作
            # add 1 channel to binary mask to be compatible with prediction
            result['mask'] = result['mask'].float().unsqueeze(0)
        result['filename'] = str(img_path)
        # print_range(result['image'].numpy(), result['mask'].numpy())
        return result

```
When running the training, I encountered the issue shown in the screenshots. 
In the first screenshot, I tried to print the type of the `transforms` before and after the judgement chunk. As your can see, after the judgement, the `transforms`  is no longer the supposedly albu.Compose object but some kind of `function` instead.  As a result, it could not accept `input: dict` as kwargs and throw out error as shown by the second screenshot. 

But after I removed the `not` in the `elif not isinstance(transform, AugmentorCompose):`, the issue went away and the training is running smoothly. 

Based on these observation, I assumed that the `not` may not be in the right place. 

Hope I explained clearly.

**Comment by bagxi** [comment]
```
if self.transforms:
    result = self.transforms(result)
```

**Comment by baibaidj** [comment]
> ```
> if self.transforms:
>     result = self.transforms(result)
> ```

Thank you. With your suggestion and the original catalyst lib, my code can run smoothly. 
I think I was misled by the segmentation-tutorial which used **result like follows:

![屏幕快照 2020-05-20 上午10 52 14](https://user-images.githubusercontent.com/24452296/82399630-2c702c00-9a88-11ea-8c36-3d83d137bc6d.png)

Anyway, thank you again. I will close this issue.

**Comment by baibaidj** [comment]
> ```
> if self.transforms:
>     result = self.transforms(result)
> ```

When I use Albumentations package for data augmentation,  I will get an error with this line of code as follows:

```
File "/home/xxx/git/semseg/catalyst_pneumonia/dataset.py", line 59, in __getitem__. 
  result = self.transforms(result) 
File "/home/xxx/miniconda3/envs/py36/lib/python3.6/site-packages/albumentations/core/composition.py", line 164, in __call__  
  assert isinstance(force_apply, (bool, int)), "force_apply must have bool or int type"   
 AssertionError: force_apply must have bool or int type
```

Please refer to https://github.com/albumentations-team/albumentations/blob/26958c4d3261f911b35175721371e07c8c2b0bb8/albumentations/core/composition.py#L164

So I have to use input the result as **kwargs.
