### ISSUE TITLE
Warning: Error in .check_sm:

### ISSUE THREAD

**Issue by OlivMC** [catalyst-team/catalyst#817]
## 🐛 Bug Report

Hi ^^
First I appology cause I'm quite noob in R and informatics...

I obtain this error message when trying to compensate FCS files from a Mass Cytometry experiment :
Warning: Error in .check_sm:
The supplied spillover matrix seems to be invalid.
All isotopes should appear in `isotope_list`.
  108: stop
  107: .check_sm
  106: .local
  105: plotSpillmat
  103: .local
  102: CATALYST:lotSpillmat
  100: renderPlotly [server-compensation.R#302]
   99: func
   96: func
   83: origRenderFunc
   82: output$plotSpillmat
    2: runApp
    1: CATALYST::launchGUI

### How To Reproduce
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("CATALYST")
library(CATALYST)
library(cowplot)
library(flowCore)
library(ggplot2)
library(SingleCellExperiment)
install.packages("V8")
CATALYST::launchGUI()

There, uploading and channels selection and deconvolution operate properly, but spillover estimate fails.

 

#### Screenshots

![image](https://user-images.githubusercontent.com/62833347/82442593-40278c80-9aa0-11ea-8df8-4e23dd338c9a.png)

### Expected behavior

Edit spillover matrix from my experiment

### Environment
Please copy and paste the output from our environment collection script
```bash
catalyst-contrib --collect-env
# or manually
wget https://raw.githubusercontent.com/catalyst-team/catalyst/master/catalyst/contrib/scripts/collect_env.py
python collect_env.py
```
(or fill out the checklist below manually).

```bash
# example checklist, fill with your info
Catalyst version: 1.10.3
PyTorch version: ?
TensorFlow version: ?
TensorBoard version: ?
OS: WINDOWS 10 pro 64bits
Python version: ?
CUDA runtime version: 640
Nvidia driver version: 26.21.14.3200
cuDNN version: 10.1.120
```

**Comment by OlivMC** [comment]
Dears, I updated my RStudio version to V4 (1.2.5042) and installed Rtools40 consequently, and now, the GUI environnement of CATALYST even refuses to launch, showing this message:
Error : 'launchGUI' is not an object exported from 'namespace:CATALYST'
An idea why ? Please help ! 
Thx in advance
Olivier

**Comment by bagxi** [comment]
Sorry but you mix up packages. What you need is https://github.com/HelenaLC/CATALYST
