### ISSUE TITLE
Distributed fails in Jupyter Notbook on PyTorch 3.6 SageMaker Env

### ISSUE THREAD

**Issue by franz101** [catalyst-team/catalyst#821]
Hi I tried installing the latest branch:
!pip install --upgrade -q git+git://github.com/catalyst-team/catalyst.git

Still if I execute with distribution set to True. No training will take place... It won't even  train an epoch.

Even though I have 8 GPUs.
I saw the related issues and pull requests: #767 #735

See the set up in the screenshots.

<img width="881" alt="Screenshot 2020-05-24 at 07 22 13" src="https://user-images.githubusercontent.com/18228395/82746501-b83bce00-9d90-11ea-8daf-231d5cc2dbc9.png">
<img width="651" alt="Screenshot 2020-05-24 at 07 20 43" src="https://user-images.githubusercontent.com/18228395/82746504-ba059180-9d90-11ea-9d50-84ed778a3c10.png">
<img width="609" alt="Screenshot 2020-05-24 at 07 20 07" src="https://user-images.githubusercontent.com/18228395/82746505-bbcf5500-9d90-11ea-91dc-d3dadafe3ecb.png">

**Comment by bagxi** [comment]
https://docs.fast.ai/distributed.html#prepare-your-script
> Distributed training doesn’t work in a notebook

**Comment by franz101** [comment]
@bagxi thank you so much. I was kinda expecting it to be the reason :D 

though I didn't read it in the original documentation. will try again soon and give feedback.
