### ISSUE TITLE
Do we have any plans to support custom data-class batch? 

### ISSUE THREAD

**Issue by AlekseySh** [catalyst-team/catalyst#846]
**Do we have any plans to support custom data-class batch?** 

I used custom dataclass batch and I faced with 2 problems:
1. There is no special logic into the Runner:
```
def _run_batch(self, batch: Mapping[str, Any]) -> None:
    """
    Inner method to run train step on specified data batch,
    with batch callbacks events.
    Args:
        batch (Mapping[str, Any]): dictionary with data batches
            from DataLoader.
    """
    if isinstance(batch, dict):
        self.state.batch_size = next(iter(batch.values())).shape[0]
    else:
        self.state.batch_size = len(batch[0])
```
2. There is a problem with moving such batch to needed device

So, do we have any plans to support usecase above?

**Comment by AlekseySh** [comment]
To overcome these issues I did the following:
1. I added `__getitem__` method to my dataclass
2. I reimplement `_handle_batch` method of `Runner` to moving data to needed device

**Comment by Scitator** [comment]
🤔 btw, do you have any proposals for correct dataclass support? I just don't think, that such trick are good practice
But it looks like, we are ready to for bath_size handling update...

what do you think about extra method, that will return `batch_size_fn(batch) -> int` for stage-loader... with lru cache?
```
@lru_cache(n=3)
def _auto_batch_size_fn(self, loader, batch):
   # some very complicated logic to return `batch_size_fn`
```
