### ISSUE TITLE
some bugs in LRFinder

### ISSUE THREAD

**Issue by ivbelkin** [catalyst-team/catalyst#85]
In case of default value for `LRFinder` parameter `n_steps=None` training terminates with
```bash
File "/home/ivb/Repos/contrib/catalyst/catalyst/dl/callbacks/schedulers.py", line 188, in on_loader_start
    self.n_steps = self.n_steps or len(state.loader)
AttributeError: 'RunnerState' object has no attribute 'loader'

```

To reproduce just replace sheduler section in `examples/cifar_simple/config.yml` with
```yaml
scheduler:
  callback: LRFinder
  final_lr: 10
```
Also doc for `LRFinder` contains unused parameter `init_lr`.

**Comment by ivbelkin** [comment]
I'll fix this after approving bug status.
In case of `init_lr` there are two options: use it or remove doc string

**Comment by Scitator** [comment]
So, after some investigation on "where the hell state.loader is?" I have fix this bug...(new state API issue)
Sorry ;)

And you was right about `init_lr` docstring, it was deprecated stuff
