### ISSUE TITLE
`process_bert_output` device bug

### ISSUE THREAD

**Issue by fursovia** [catalyst-team/catalyst#885]
## 🐛 Bug Report
`pooling` and `bert_output` objects in `process_bert_output` function can be on different devices.

Something like this will solve the issue. 

```python
pooling = (
    LamaPooling(groups=pooling_groups, in_features=hidden_size)
    if pooling_groups is not None
    else None
)

if pooling is not None:
    pooling = pooling.to(bert_output[0].device)

...
```

However, this is not the best way to do it :)

**Comment by Scitator** [comment]
Hi, thanks for the issue. Do you have any minimal example on this issue?
Looks like your solution should help, would you like to make a fix PR?
