### ISSUE TITLE
Should this repo be 100% flake8 compliant?

### ISSUE THREAD

**Issue by cclauss** [catalyst-team/catalyst#9]
Very few issues to address https://travis-ci.com/Scitator/prometheus/jobs/149428974#L465

**Comment by Scitator** [comment]
Really interesting question, you know.
I am not sure if we should make it pure flake8 compliant, cause sometimes lambdas are really great.
Nevertheless, `C901` is important one. So, maybe we should just exclude shampoo for now.

**Comment by cclauss** [comment]
E731 does not object to lambdas.  It merely objects to assigning lambdas to variables.  It recommends defining a function instead.
