### ISSUE TITLE
TensorboardLogger incorrect horizontal axis view 

### ISSUE THREAD

**Issue by tdtce** [catalyst-team/catalyst#906]
## 🐛 Bug Report

TensorboardLogger in batch logger mode displays horizontal axis by samples, which is inconvenient. 

### How To Reproduce
1. import logger
`from catalyst.dl.callbacks import TensorboardLogger`
2. make TensorboardLogger callback  with batch logger mode
`calback_tb = TensorboardLogger(metric_names=["loss"], log_on_batch_end=True)`
3. add callback into runner
`
runner.train(model=model,
    criterion=criterion,
    optimizer=optimizer,
    callbacks=[calback_tb])
`

#### Screenshots
In Tensorboard i have that plot:
![Screenshot from 2020-08-06 19-31-24](https://user-images.githubusercontent.com/20914357/89558668-2b47d300-d81d-11ea-9af7-f3ef13ad2b42.png)
Horizontal axis displays amount of samples (10k samples overall), I guess it should show amount of batches. 

#### How to fix 
To fix it, you can change the step parameter in [that](https://github.com/catalyst-team/catalyst/blob/34a69e568c69ab1eb364fc1646623f75756c82d2/catalyst/core/callbacks/logging.py#L220) line from `runner.global_sample_step` to `runner.global_batch_step`

**Comment by Scitator** [comment]
Hi, thanks for your question.
In `batch` some all our loggers displays metrics in `per samples` mode, by this solution you could compare pipelines with different batch size correctly.
