### ISSUE TITLE
No module named 'catalyst.data.cv.transforms'

### ISSUE THREAD

**Issue by kornellewy** [catalyst-team/catalyst#911]
from typing import Callable, List, Tuple
import os
import torch
import catalyst
from catalyst.dl import utils
print(f"torch: {torch.__version__}, catalyst: {catalyst.__version__}")
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # "" - CPU, "0" - 1 GPU, "0,1" - MultiGPU
SEED = 42
utils.set_global_seed(SEED)
utils.prepare_cudnn(deterministic=True)

give :

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-10-473c57d966b7> in <module>()
      3 import torch
      4 import catalyst
----> 5 from catalyst.dl import utils
      6 print(f"torch: {torch.__version__}, catalyst: {catalyst.__version__}")
      7 # os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # "" - CPU, "0" - 1 GPU, "0,1" - MultiGPU

6 frames

/usr/local/lib/python3.6/dist-packages/catalyst/data/cv/__init__.py in <module>()
      4 from catalyst.tools import settings
      5 
----> 6 from catalyst.data.cv.transforms.torch import (
      7     Compose,
      8     Normalize,

ModuleNotFoundError: No module named 'catalyst.data.cv.transforms'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
-----------------------------

**Comment by Scitator** [comment]
fixed, check `20.08.1` version please. `20.08` was removed.
