### ISSUE TITLE
Hydra/OmegaConf configuration structure

### ISSUE THREAD

**Issue by otherman16** [catalyst-team/catalyst#912]
## 🚀 Feature Request

[Hydra](https://hydra.cc) provides interesting [features](https://hydra.cc/docs/intro) to create hierarchical configuration by composition and override it through config files and the command line.
I think that this ability will be useful for catalyst pipelines with configuration file.
Now one configuration file contains all pipeline settings inside, but if we split it to for example model_params/data_params/runner_params/and so on then we will be able to get configuration structure distributed in sence. This will allow us to quickly run experiments with different combinations of settings and also change settings in the command line

Example pipeline:
```bash
pipeline/
    conf/
        config.yaml
        model/
            resnet.yaml
            mobilenet.yaml
            efficientnet.yaml
        data/
            imagenet.yaml
            coco.yaml
        runner/
            runner1.yaml
            runner2.yaml
    src/
        callbacks.py
        model.py
        ...
```
Run example:
```catalyst-dl run config=conf/config.yaml model=resnet data=imagenet runner=runner1```

### Possible solution
1. Create class HConfigExperiment class
2. Change catalyst-dl run script

### Motivation

Combining configuration parts for different experiments. Change settings in command line.

### Additional context

I've already written simple MNIST classification pipeline with hydra configuration structure. But I can run it only with ```python train.py``` command.

**Comment by omry** [comment]
Hi,
Definitely take a look at [Structured Configs](https://hydra.cc/docs/next/tutorials/structured_config/intro) in Hydra 1.0.
It's taking Hydra to the next level, and is especially useful for frameworks.

**Comment by Scitator** [comment]
@otherman16 Hi, looks interesting, but how does it differ from current multi-config behaviour?
```bash
catalyst-dl run config conf/config-main.yaml conf/config-model-resnet.yaml conf/config-extra-new-name.yaml
```

**Comment by otherman16** [comment]
@Scitator They are almost the same but with Hydra/OmegaConf you can also:
1. Change specific settings in command line. Example:
```catalyst-dl run config=conf/config.yaml model=resnet data=imagenet runner=runner1 model.resnet=50/101/...```
2. Command line [Tab Completion](https://hydra.cc/docs/next/tutorials/basic/running_your_app/tab_completion)
3. Select default configuration
4. As say @omry [Structured Configs](https://hydra.cc/docs/next/tutorials/structured_config/intro) + [Object Instantiating](https://hydra.cc/docs/next/patterns/instantiate_objects/instantiate_with_structured_config)
5. [Multi-run](https://hydra.cc/docs/next/tutorials/basic/running_your_app/multi-run) different configurations with one command
6. And other features (I don't know hydra well enough).

One more advantage of using Hydra/OmegaConf is that Hydra can say 'Catalyst uses us' and Catalyst can also say 'We use Hydra'. So the community will grow. And we will be happier =)

**Comment by omry** [comment]
Hi @Scitator.
In addition the good list @otherman16 put up, here are a few extra things:
* Launcher plugins can launch any Hydra app to different places without changing the code. There are already plugins for SLURM, Joblib (local parallel execution), Redis Queue and more. There is a Ray based Launcher plugin coming that will support launching to AWS.
* Advanced Sweeper plugins like Ax and Nevergrad lets you perform hyper parameter optimization on any Hydra app without changing its code.
* Automatic working directory management
* Automatic logging configuration

ML Frameworks often solves many similar problems, Hydra aims to reduce the effort duplication, and to create a standardized and powerful interface. That interface is more powerful than what most framework will bother to create and it is completely generic. This means users that learn how to use Hydra will feel right at home with any other Hydra powered application.
I can tell you that a few high profile ML frameworks are already switching to Hydra. ([fairseq](https://github.com/pytorch/fairseq) has an internal prototype with Hydra at advanced stages), and [mmf](https://github.com/facebookresearch/mmf) is using OmegaConf and will switch to Hydra once Hydra catches up on a few features it have implemented and are missing.
There are also some Non-Facebook frameworks that are switching or switched like [NVIDIA's NeMo](https://github.com/NVIDIA/NeMo), [deepspeech.pytorch](https://github.com/SeanNaren/deepspeech.pytorch) and more.

I am happy to answer any questions you may have in the [Hydra chat](https://hydra-framework.zulipchat.com/).

**Comment by Scitator** [comment]
Deal, guys, it could be interesting...
@otherman16 would you like to make a PR with such functionality? Or at least discuss it implementation properly?
Would you like to join [our slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) and discuss it with the team?

I would be glad to see @omry there too! Config API is essential part of the Catalyst framework and we could possible bring our libraries to new level together (we have a lot of things-to-be-done with configs 😂 ).

**Comment by otherman16** [comment]
@Scitator Ok. Moving to slack now.

**Comment by Scitator** [comment]
nope, we are working on it ;)

**Comment by Scitator** [comment]
looks like done :)
