### ISSUE TITLE
How to do automatic mixed precision training?

### ISSUE THREAD

**Issue by janvainer** [catalyst-team/catalyst#914]
I could not find any docs for mixed precision training and how it plays with distributed training.
I am aware of issues that work with amp, or suggest to update to newest pytorch with integrated support for mixed precision, but it is unclear in what state we are now. 
Is the approach mentioned in [this issue](https://github.com/catalyst-team/catalyst/pull/183) the recommended way for now? (10.8.2020)

```
model, optimizer = amp.initialize(model, optimizer, opt_level="O1")

runner = SupervisedRunner()
runner.train(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    ...)
```

**Comment by Scitator** [comment]
Hi, you could just run
```python
model, optimizer, etc = ...

runner.train(..., fp16=True, distributed=True)
```

Docs - https://catalyst-team.github.io/catalyst/api/dl.html#catalyst.dl.runner.runner.Runner.train
Code docs (I prefer them) - https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/runner/runner.py#L92#L97

Guide - https://catalyst-team.github.io/catalyst/info/distributed.html

Bunch of examples (all dl_z_distributed_*) - https://github.com/catalyst-team/catalyst/blob/master/tests/_tests_scripts/dl_z_distributed_13.py

Aaaand, as far as I remember we also have examples for fp16 in classification & segmentation tutorials https://github.com/catalyst-team/catalyst#tutorials

I hope, it could help you :)

**Comment by janvainer** [comment]
Hi, thanks. :)

**Comment by Scitator** [comment]
btw, I have also updated [minimal examples](https://github.com/catalyst-team/catalyst#minimal-examples) with fp16 and colab links :)
