### ISSUE TITLE
Fatal error caused by setting `torch.backends.quantized.engine = "qnnpack"`

### ISSUE THREAD

**Issue by BloodAxe** [catalyst-team/catalyst#929]
It seems this line breaks pytorch 1.6 under Windows:

https://github.com/catalyst-team/catalyst/blob/40faab689795c68b9ba8de0d9fd59ec8f7a0e19a/catalyst/dl/utils/quantization.py#L23

A reason could be due to lack of qnnpack support on windows. It may be a good idea to:
- Avoid global state change and assign quantization backed inside quantization function
- Let user change the quantization engine via parameter

**Comment by Scitator** [comment]
Fixed :)
