### ISSUE TITLE
Wrong order of embeddings in CMC score callback

### ISSUE THREAD

**Issue by jzakirov** [catalyst-team/catalyst#938]
## 🐛 Bug Report
Order of elements in [cmc_score](https://github.com/catalyst-team/catalyst/blob/34a69e568c69ab1eb364fc1646623f75756c82d2/catalyst/utils/metrics/cmc_score.py) function:
1. query_embeddings: torch.Tensor,
2. gallery_embeddings: torch.Tensor,
3. conformity_matrix: torch.Tensor,
4. topk: int = 1

But in [CMCScoreCallback](https://github.com/catalyst-team/catalyst/blob/34a69e568c69ab1eb364fc1646623f75756c82d2/catalyst/utils/metrics/cmc_score.py) you call it with another order of arguments:
```
            metric = self._metric_fn(
                self._gallery_embeddings,!!!
                self._query_embeddings,
                conformity_matrix,
                key,
            )
```

But bug never comes alone, so this works, because `conformity_matrix` in `CMCScoreCallback` also has wrong shape `(gallery_size, query_size)` instead of `(query_size, gallery_size)`.

## Solution
In CMCScoreCallback:
```
            metric = self._metric_fn(
                self._query_embeddings,
                self._gallery_embeddings,
                conformity_matrix,
                key,
            )
```
And 
```
conformity_matrix = self._query_labels.reshape(-1, 1) == self._gallery_labels
```

**Comment by Scitator** [comment]
@AlekseySh and @elephantmipt fyi :)

**Comment by elephantmipt** [comment]
Hi @zakajd! Thank you for noticing this problem! Can you please review PR with a fix before we merge it?
