### ISSUE TITLE
Problem with LovaszLossBinary

### ISSUE THREAD

**Issue by Dokholyan** [catalyst-team/catalyst#964]
There is a problem with LovaszLossBinary(maybe there are similar problems with LovaszLossMultiClass and LovaszLossMultiLabel)

If I train a model using lovasz loss, I don't have any problems. If I use a combination of several losses(for example bce, dice, iou) and use MetricAggregationCallback, I will get such error:
================================================
RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence element 3 in sequence argument at position #1 'tensors'
================================================
I use this code:
++++++++++++++++++++++++++++++++++++++++++++++++
criterion = {
    "dice": DiceLoss(),
    "iou": IoULoss(),
    "bce": nn.BCEWithLogitsLoss(),
    "lovasz": LovaszLossBinary()
}
callbacks = [
    # Each criterion is calculated separately.
    CriterionCallback(
        input_key="mask",
        prefix="loss_lovasz",
        criterion_key="lovasz"
    ),
    CriterionCallback(
        input_key="mask",
        prefix="loss_iou",
        criterion_key="iou"
    ),
    CriterionCallback(
        input_key="mask",
        prefix="loss_bce",
        criterion_key="bce"
    ),
    CriterionCallback(
        input_key="mask",
        prefix="loss_dice",
        criterion_key="dice"
    ),

    MetricAggregationCallback(
        prefix="loss",
        mode="weighted_sum",
        metrics={"loss_dice": 1.0, "loss_iou": 1.0, "loss_bce": 0.8, "loss_lovasz": 1.0},
    ),
]
++++++++++++++++++++++++++++++++++++++++++++++++
I think it caused by the fact that this loss returns 'torch.cuda.FloatTensor' while other return 'torch.cuda.DoubleTensor'
I solve this problem by using a simple helped class:
++++++++++++++++++++++++++++++++++++++++++++++++
from catalyst.contrib.nn.criterion import LovaszLossBinary

class LovaszLoss(nn.Module):
    def __init__(self, per_image=False):
        super(LovaszLoss, self).__init__()
        self.lovasz = LovaszLossBinary(per_image)
    
    def forward(self, logits, target):
        return self.lovasz(logits, target).double()
++++++++++++++++++++++++++++++++++++++++++++++++
After this, all work well

**Comment by Dokholyan** [comment]
Sorry for the formatting, I didn't expect this :-(

**Comment by Scitator** [comment]
🤔  @Dokholyan 
could you please bring us a minimal example to reproduce the error? something from https://github.com/catalyst-team/catalyst#minimal-examples would be good enough ;)
