### ISSUE TITLE
How to predict an image without using predict_loader?

### ISSUE THREAD

**Issue by aspenstarss** [catalyst-team/catalyst#965]
I wanted to integrate catalyst code into my system, and it was a sequence prediction. So I had to feed a single image from last stage into the model.
I have try this code, but the results seem to be different by using `predict_loader`. 
Can you give me a example to predict?
Thanks!

```
model = ....
model.load_state_dict(torch.load(model_checkpoint)["model_state_dict"])

logits = model.predict(image)
pred_ = logits[0].sigmoid().squeeze(0)
pred_ = pred_.detach().cpu().numpy()
pred = (pred_ > threshold).astype(np.int32)
```

**Comment by Scitator** [comment]
Hi, nice question!
Generally speaking, the whole model predict logic stored under `Runner.predict_batch`, you could check the example [here](https://github.com/catalyst-team/catalyst#getting-started).

For example, the [source code](https://github.com/catalyst-team/catalyst/blob/master/catalyst/runners/runner.py#L331#L332) ;)

**Comment by Scitator** [comment]
Colab example - https://colab.research.google.com/drive/1A_JVXdnecanWCM74qi-KqUn0boElvISk?usp=sharing

**Comment by Scitator** [comment]
btw, dont you mind to [join our slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for collaboration? It would be much easier to communicate with each other ;)
Github is great tool for code review, but slack is better for questions handling.

**Comment by TimbusCalin** [comment]
@Scitator very nice colab and @aspenstarss very nice question; I was looking for the exact same question + solution and it appears I have found it

**Comment by TimbusCalin** [comment]
> I wanted to integrate catalyst code into my system, and it was a sequence prediction. So I had to feed a single image from last stage into the model.
> I have try this code, but the results seem to be different by using `predict_loader`.
> Can you give me a example to predict?
> Thanks!
> 
> ```
> model = ....
> model.load_state_dict(torch.load(model_checkpoint)["model_state_dict"])
> 
> logits = model.predict(image)
> pred_ = logits[0].sigmoid().squeeze(0)
> pred_ = pred_.detach().cpu().numpy()
> pred = (pred_ > threshold).astype(np.int32)
> ```

I assume you might have forgotten to use the preprocessing steps for you single image? I expect that, given the correct load of the model, single prediction could work in absence of predict_loader()

**Comment by TimbusCalin** [comment]
@aspenstarss have a look at this prediction example:

```
import albumentations as albu
from tqdm import tqdm

def transforms_for_test():
    return [albu.Resize(512, 512, p=1),
            albu.Normalize(mean=(0.485, 0.456, 0.406),std=(0.229, 0.224, 0.225), p=1),
            ToTensor(num_classes=len(CLASSES))]

def compose(transforms_to_compose):
    # combine all augmentations into single pipeline
    result = albu.Compose([item for sublist in transforms_to_compose for item in sublist])
    return result

test_transforms = compose([transforms_for_test()])

#In order to predict on batches, make sure you provide a dictionary not an image
for image_path in tqdm(TEST_IMAGES):
    image = utils.imread(image_path)
    image = test_transforms(image=image)["image"]
    #Expanding the dimensions (512,512 since that is the resolution the network was trained on)
    image = torch.reshape(image,(1,3,512,512))
    #The input is an input image
    input_image = {"image": image}
    #The output is again a dictionary
    output = runner.predict_batch(input_image)
    #The logits(we squeeze them as the prediction is (1,4,512,512) => transform it to (4,512,512)))
    logits = output["logits"].squeeze()
    #The result(argmaxed)
    result = torch.argmax(logits,dim=0).cpu().numpy()
```

This is how to predict on a single image if you want to read them sequentially.

@Scitator  tell me if I can help you to document(have this short example) as a demonstration for single prediction, if you deem it approapriate.
