### ISSUE TITLE
Tensorboard resets step counter if the training restarted with runner.train(resume=last_full.pth)

### ISSUE THREAD

**Issue by asanakoy** [catalyst-team/catalyst#970]
## 🐛 Bug Report
Using SupervisedRunner.
If you restart training by loading the full checkpoint last_full.pth and `runner.train(..., resume=last_full.pth)`, then tensorboard will restart the iteration ciunter to zero, which will correupt the plot.

#### Screenshots

![image](https://user-images.githubusercontent.com/1690869/96940653-988c0b80-14d0-11eb-8cfe-a2da7cd093c0.png)

### Expected behavior
Tensorboards continues to log from the latest iterationa and not from 0-th.

### Environment

```bash
Catalyst version: 20.10.1
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2
TensorFlow version: N/A
TensorBoard version: 2.3.0
OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
CMake version: version 3.16.3
Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
```

**Comment by Scitator** [comment]
Hi,
Thanks for your issue contribution. Based on Catalyst design, every `.train` is a new experiment run. 
If you would like to run a multi-stage experiment and transfer the model from one stage to another, you could try our [Config API example here](https://github.com/catalyst-team/catalyst/tree/master/examples/cifar_stages), or... [try out Kittlylyst example here](https://github.com/Scitator/kittylyst/blob/master/demo.ipynb), looks like we need to setup Catalyst-one too 😂
